var highLights = [
"2tTQgaHlawE+Elroy \"Crazy Legs\" Hirsch", 
"WWp7P6o8rME+#25 - Elroy \"Crazy Legs\" Hirsch", 
"kuiLn3K8xuw+Camp Randall 100: Elroy Hirsch", 
"YyLGo7h50i0+Crazylegs (1953) | Football Drama | Elroy \"Crazylegs\" Hirsch | NFL L.A. Rams | Lloyd Nolan", 
"7DUAnQHZBGk+Every Herb Adderley Touchdown | Herb Adderley Highlights", 
"UdqlqJvqQXY+Every Herb Adderley Interception (Playoffs) | Herb Adderley Highlights", 
"exIkgatFAs4+Troy Aikman Career Highlights", 
"UijQqvDg320+Troy Aikman Highlights", 
"rH1PMxNgEgw+Top 10 Josh Allen Plays From 2022 NFL Season! | Buffalo Bills", 
"RcmpwfcKNGE+Josh Allen's Top Plays At The Bye | 2022 Season | Buffalo Bills", 
"iOxwwr1k4Dc+5+ minutes of Josh Allen being athletic", 
"DFcWMC9vkZg+Larry Allen Prevents Pick-Six", 
"46PWiPKAXus+#85: Marcus Allen | The Top 100: NFL's Greatest Players (2010) | #FlashbackFriday", 
"6f-2NXYHtIM+Bambi - Lance Alworth Career Highlights", 
"_BuUzxdHsZk+LANCE ALWORTH SAN DIEGO CHARGERS 1962-1970 (ARKANSAS)", 
"WbsAtjR7ZZ0+Every Lance Alworth Touchdown with the Cowboys | Lance Alworth Highlights", 
"CZ-avEmn-mk+Justin Tucker & Morten Andersen are Kicking Kings | NFL Generations", 
"dS6EebiYklE+One Kick from Each Year of Morten Andersen's Career", 
"2a5_86Ko-Zo+Take It To The Top (Brian Hansen & Morten Andersen) 1985", 
"cZg28uxdSTA+Doug Atkins Highlights", 
"1XALQxRQAgw+Doug Atkins. #9 All-Time Pass Rusher in NFL History", 
"YlHkwS7fJAk+Chicago Bears Doug Atkins", 
"uVPNrS6qeu4+Remembering Vol legend Doug Atkins", 
"rssVFHtO8_Q+Steve Atwater stops Christian Okoye in his tracks | #NFL100 Greatest Plays", 
"0iOqS79PXd0+Denver Broncos Top 20 Hits Of All Time", 
"T0WpgW9PLfs+Steve Atwater Highlights!!!", 
"dDwa48dMOjw+Red Badgro: Hall of Fame Football End and Defensive End", 
"H5itKxb4hts+2012 Texas Tech Hall of Fame: Bam Morris", 
"_Kti79Oh-d4+Champ Bailey 'locked down an entire half of the field'  | Broncos Top 100", 
"rQKTopu7IIc+Ronde Barber \"Momentum\" Career Highlights | NFL Legends", 
"cBEgkaWWBaQ+Lem Barney: A Lions Legend", 
"KtW8dtTsyRo+Lem Barney Highlights", 
"sOAAQAGSDUo+The Motown Marauder - Lem Barney Career Highlights", 
"xOqTecUtg80+LEMUEL \"LEM\" BARNEY DETROIT LIONS 1967 - 1977", 
"VUUCfNKJ2Og+Lem Barney on Marvin Gaye's football skills", 
"7RBCrOK-AAU+Cliff Battles: Hall of Fame Football Halfback and Defensive Back", 
"R9b4TFnHx28+TEXAS : #1 Duncanville vs 5A #1 South Oak Cliff | BATTLE of Defending State Champs 🔥🔥 Highlight Mix", 
"6O-j6eWqkG8+Use These Pokemon to Defeat Cliff Strongest Team Efficiently in Pokemon GO", 
"Z6vV-t3-EZM+Sammy Baugh Highlights", 
"xum9jIYyOxk+Sammy Baugh Highlights", 
"Lm0zxrWIhvs+Redskins Historian Mike Richman w/ Bobby Beathard, 1 of the 80 Greatest Redskins", 
"J0U6xiEoiq0+Bobby Beathard \"10 for 80\" segment", 
"ohvbX-1bAcg+Bobby Beathard feature, 1982", 
"rq5HMMvuVtw+Joe Gibbs: “You get Bobby Beathard? You get Super Bowls”", 
"KOyfgo5DeIM+Chuck Bednarik Highlights || Concrete Charlie, The Last Of The 60 Minute Men", 
"o1EHius5Y88+Chuk BEDNARIK plaquage Frank Grifford", 
"Qo0WUCcs_gs+NFL Films Presents: Concrete Charlie", 
"ZDx3cv5OdD4+Le'Veon Bell Top 25 Career Highlights", 
"eQRHO6i3-j0+Le'Veon Bell | Steelers Highlights", 
"vyiI85y0MFA+Bert Bell Senior Championship 2022 (*EXTRA ANGLE*) Darby Township vs Springfield. Nov 19, 2022", 
"bTZcfN3sH68+Bert Bell Championship Highlights 2019. “I’m A Champion”", 
"q82vYZup2hY+Through The Eyes of Bobby Bell: A Tale of Football, Family, & Inclusion", 
"3CttRGMOcAI+Mike Garrett and Bobby Bell", 
"LrITL2jqeXA+RAYMOND BERRY NFL CAREER HIGHLIGHTS RAYMOND BERRY NFL HALL OF FAME CAREER", 
"Qhyu5-98Hmg+Raymond Berry", 
"sCpkIsx3iI4+Raymond Berry", 
"usCM6B00fUQ+Raymond Berry's most memorable game", 
"1lRSYb-rKp4+Elvin Bethea | Oilers Tribute Week", 
"3LdJ6qdi7UQ+Elvin Bethea: Hall of Fame Football Defensive End", 
"eIgxSvzqLho+A Hall of Fame Health Care Story: Elvin Bethea", 
"VoCcC2hf6hY+Elvin Bethea's Story", 
"Y0Ehc4tjA30+OILERS legend ELVIN BETHEA dumps Barry Warner into Ice Tub", 
"y5FhCpINFyw+Jerome Bettis' Top Plays | Pittsburgh Steelers Hall of Fame Highlights", 
"68bufu87lzY+Jerome Bettis Highlights || \"The Bus\"", 
"JCu-4_Sl-Jo+Top Rookie Plays of The 2022 Regular Season | NFL Highlights", 
"Z6okhptiz_I+Philadelphia Eagles Study: LB Nakobe Dean SHOWED OUT in his starting debut | Too Small?!?!", 
"wjXvp-TWod8+Ozzie Smith Career Highlights", 
"KEdeiW6zJWY+Fred Biletnikoff Highlights", 
"1k34sHdSqS4+Top 11 Fred Biletnikoff Touchdowns", 
"4fLamuaAph0+Fred Biletnikoff: Best Hands", 
"s70SaDFo7vs+Every Fred Biletnikoff Touchdown in the Playoffs", 
"OZrWpc0OFZI+George Blanda's 1970 Miracle Season", 
"wQiBYmz66g4+George Blanda Highlights", 
"L33KL0RqKCs+Remembering George Blanda (1927-2010)", 
"ynkePYuKG3U+Top 10 Steelers", 
"n8vNkq8gNa0+Mel Blount Highlights", 
"89bptOixvjE+Jaguars All-25: #1 Tony Boselli Shutdown Hall of Fame Defensive Ends", 
"IAS8fGYWlU8+Broncos celebrate Champ Bailey, Pat Bowlen and Top 100 Team", 
"Uerk1b7zpUg+Pat Bowlen: The Mile High Legend (full special)", 
"FaBPBnOd6BM+Pat Bowlen Tribute Song \"Greatest Owner Ever\"", 
"qS8XfPh_134+Owner Pat Bowlen's impact on the NFL, Broncos", 
"x6gyB-FUU5U+Terry Bradshaw Highlights (Final Version)", 
"FwQR5MO9ipQ+Terry Bradshaw", 
"oym68dywgq0+Cliff Branch Highlights", 
"CLZlnaH1KtI+Cliff Branch", 
"uAQ4sjlaI0Y+CLIFF BRANCH 11 LONGEST NFL TOUCHDOWNS", 
"7iO0S9EzJG4+Reflecting on Gil Brandt's legendary NFL career | Pro Football Talk | NFL on NBC", 
"mzgf2LKn0B0+Cowboys computer - Gil Brandt", 
"0KArFNGrWik+Remembering an architect of 'America's Team,' Hall of Famer Gil Brandt: 1932-2023", 
"U-PMwHBobFQ+Mick Shots: Remembering Gil Brandt | Dallas Cowboys 2023", 
"hKDLKaKKpho+Robert Brazile: Houston Oilers \"Dr.Doom\"", 
"M1CSMAHhhUE+Robert Brazile, Nicknamed Dr. Doom, Was One of the Greatest Houston Oilers of All Time", 
"zRhss_q04SQ+NFL Hall of Famer Robert Brazile tribute video (Dr. Doom)", 
"FIQuQe34z_c+Robert Brazile | Oilers Tribute Week", 
"3aY92QF3Alg+Every Touchdown of Derrick Brooks Career", 
"QkLTG8JZHb8+Derrick Brooks Highlights | \"Journey to Canton\"", 
"Ywd3lfvQ6A8+Derrick Brooks Florida State Highlights | ACC Football Icon", 
"PWHExr-22H0+Power of Sports | Gamechangers – Bob Brown", 
"Hr-eQqL-W10+PHILADELPHIA EAGLES BOB BROWN Highlights 🦅", 
"PLZag-co1xk+5 Most Savage Offensive Linemen in NFL History", 
"reXZhtUPrd4+Remembering 'most aggressive lineman that ever played' football, Hall of Famer Bob Brown: 1941-2023", 
"9cqsIedJew4+Jim Brown's Top 5 Runs", 
"VfQUJwCo7T8+Jim Brown Career Highlights | NFL", 
"z05uHuQPQdg+How Good Was Jim Brown Actually?", 
"IJIXcaUcfTs+'NFL 100 Greatest' Game Changers: Paul Brown", 
"-Ysv6c7HUUo+A Football Life-Paul Brown", 
"lzps7eAYKl0+Paul Brown - The Father of Modern Football", 
"wEKOqcl9h1o+How Paul Brown Revived His Career In Cincinnati | A Football Life", 
"Mbr2UI4f6dI+Cleveland Browns-Cincinnati Bengals History link through Paul Brown as told by Jim Brown", 
"5GSJu6W6OnM+Value Picks: #2 Harry Carson & #1 Roosevelt Brown", 
"7WHD9Warz4g+Rosey Brown", 
"s_W-fzshKVs+Week 2: Top 3 Man-to-Man Matchups | Baldy Breakdowns", 
"v6dLAIMlehQ+Tim Brown / Career Highlights / The Silver & Black!! (pt. 1/2)", 
"3kMsNxvFKx4+Tim Brown Highlights", 
"ftOJ3Qhotr8+Tim Brown / Career Highlights / The Silver & Black!!! (pt. 2/2)", 
"LRUXB0ZZlIk+#5 Willie Brown Seals a Super Bowl for Oakland | NFL Films | Top 10 Interceptions", 
"5ialhe5DRC0+Willie Brown Highlights", 
"5lVhQ1i2a3s+Isaac Bruce Highlights (The Reverend )", 
"JPP1bqppfgI+BUCK BUCHANAN NFL HALL OF FAME CAREER BUCK BUCHANAN NFL CAREER HIGHLIGHTS", 
"eFEEBE4LoFQ+Buck Buchanan Highlights", 
"DIerg_9aemc+NFL All-Time Team: Buck Buchanan", 
"nAtAQhj0V2E+Buch buchanan highlights", 
"5G2hfvbv8u0+SEMO Football | 2018 STATS Buck Buchanan Award Winner Zach Hall Highlights", 
"EsyH8a2Ccp8+He Needs To Be Double Teamed Every Play... Buck Buchanan Winner Isaiah Land Hightlights!!", 
"MoFbhL1cKq4+Legendary Coach Don Shula & Nick Buoniconti | The Many Lives of Nick Buoniconti | HBO", 
"FJj6gzLMxgk+NFL Hall Of Famer & Dolphins' Nick Buoniconti: A Legend, Searching For Answers | Sports Illustrated", 
"jkv1i5BT30k+Collinsworth on Buoniconti \"He's a Pitbull w/ Everybody\" | The Many Lives of Nick Buoniconti | HBO", 
"ghHJyMeARuw+NFL: The Video Hall Of Famer Nick Buoniconti's Family Wants You To See | Sports Illustrated", 
"bfEPkL5MPKI+The Many Lives of Nick Buoniconti (2019) | Official Trailer | HBO", 
"lsWqX2LgXN4+DICK BUTKUS: HARDEST HITS (Old School Football)", 
"nluXKFKxBuo+Butkus   Monster of the Midway", 
"qJzEgMhU9_Q+NFL's Greatest Hits - Dick Butkus", 
"i_V1Ixe1QlI+Dick Butkus (Gladiator Mentality) Career Highlights", 
"dofmnZ5-HHs+Jimmy Butler Top 10 Plays of Career", 
"Q_SXgdDj2xY+LeRoy Butler Highlights", 
"3S0lwJIni_c+Leroy Butler Career Highlights ᴴᴰ", 
"XByoPFu7SOo+LeRoy Butler Highlights", 
"RGhHa4atfIM+Highlights: LeRoy Butler heading to Pro Football Hall of Fame", 
"2BG7oQ_wdQ8+The Best And Worst Defensive Back Plays Of The NFL's 2023 Week 1 With Darius Butler", 
"Kz1nhPZLyHw+Top Ten Earl Campbell Plays of All Time", 
"x7DKVvw6XYA+Earl Campbell #3 Power Back of all time.", 
"RKUwALU0rOY+NFL 100: Earl Campbell's Record Setting Monday Night", 
"V3Gvevv5La4+Tony Canadeo: Hall of Fame Football Halfback and Quarterback", 
"p7ZtyRazn3g+Tony Canadeo", 
"9hZeRk9W8vo+Best Moments of the Green Bay Packers 2022-23 Season", 
"McZxTbaiEaI+Harold Carmichael Highlights", 
"BQwqIwWxyTo+Harold Carmichael's Ultimate Hall of Fame Career Highlights | Philadelphia Eagles", 
"QcEoQ0NPR1E+PHILADELPHIA EAGLES HAROLD CARMICHAEL [Full Highlights] 🦅", 
"5bxDWUIR8i0+US Presidents and Scout plays Mario Kart Wii CTGP Revolution", 
"2QHiqSO2E3U+US Presidents and their \"friends\" plays Mario Party 7  (ft. John Bradshaw Layfield)", 
"VroFAx5GGFk+Joe Burrow Top Plays of the 2022 Season", 
"VNRejCsxW3I+Top Plays from Week 1 | NFL 2023 Highlights", 
"9E0-VquozEM+The Harry Carson Tribute", 
"346ArUcMZTE+Harry Carson Giants LB 1989 HD", 
"Ixjpn_cElk4+New York Giants Miracle Win! Harry Carson Touchdown Fumble Recovery Vs Kansas City Chiefs 10/21/1979", 
"SHjf0L7R0o8+Cris Carter - All He Does is Catch TOUCHDOWNS!!! (Career Highlights) Vol. 2 (1/3)", 
"U-7q6g8kgXA+Cris Carter - All He Does is Catch TOUCHDOWNS!!! (Career Highlights) Vol. 2 (2/3)", 
"Nv1xygbkYgI+Dave Casper (The Ghost) NFL Legends", 
"am1x7Yy6aBc+KEN STABLER TO DAVE CASPER - NFL ULTIMATE CONNECTIONS", 
"FjCOEMjxXws+When Football Was Football - Guy Chamberlin: The Mysterious Disappearance of the NFL's...", 
"qfczQovODz8+Wilt Chamberlain Highlights | THE GOAT IN HIS PRIME | 4K |", 
"1WsCtyLGg1w+Wilt Chamberlain's INSANE Athleticism Caught on Film!", 
"s8OgsKX3sMc+Who did Guy Chamberlin play for?", 
"x78xvHs85Yw+What position did Guy Chamberlin play?", 
"AQjG2Lc-Lk0+Jack Christiansen Highlights", 
"tqGOfto5lDo+Detroit Lions: Jack Christiansen was One of the Best", 
"EnkAv5VGJ54+Jack Christiansen - Goalkeeper Highlights (2022)", 
"4IMENDE2fs8+Jack Christiansen '25 - 2022 Soccer Highlights (Goalkeeper)", 
"cK4VpguWPwM+Earl \"Dutch\" Clark - The Best All Around Player in NFL History", 
"XU1HX-bGV7g+College Football Top 100 Plays of the 2022-23 Season ᴴᴰ", 
"I_jhqi_DGoY+Earl (Dutch) Clark – The Detroit Lions’ First Gridiron Great", 
"uyleQGn2MZ4+Brawl at Dutch Clark ends 47th Pueblo Cannon Game Early", 
"1qX5ynhME28+Family of southern Colorado football legend heading to Super Bowl", 
"XBSUyWORqtM+George Connor Hall of Fame Induction Documentary", 
"VbWkRXKoUZY+GEORGE CONNOR Let The Club Swing Bump Up Drill", 
"1D_H0PnttzA+Connor Bedard Makes His Chicago Blackhawks Training Camp Debut | CHGO Blackhawks Podcast", 
"u584EsAhDJE+Top Of The Club Swing Face Positions", 
"eRBfaL2_qDM+Jimmy Conzelman: Hall of Fame Football Quarterback", 
"fTyDyaxWqYQ+When Football Was Football - Jimmy Conzelman: NFL's Most Unique Coach", 
"pbRoQ1cZDXo+Jim Brown Highlights (Final Version)", 
"9cqsIedJew4+Jim Brown's Top 5 Runs", 
"U_NyIcS7nQw+Air Coryell: The Revolutionary Offense Always One Step Away From Glory | NFL Throwback", 
"11vBZViLToU+Don Coryell - Offensive Innovator", 
"g-oOqfyn15c+Don Coryell - Taking the Passing Game to the Next Level", 
"FXIOI9r_jsc+Jimbo Covert Tribute Video", 
"MZ_cu_OQaLk+Inside the 50: Jimbo Covert", 
"66uKW7t9rNc+Pitt Man | Jimbo Covert", 
"fHfIAChNAwc+The GREATEST Coaching Meltdown in NFL History (Bill Cowher)", 
"uVZ6DR0Znos+Lou Creekmur Career Overview", 
"IBJbYcGGIzM+World's Championship Football Game (Cleveland Browns at Detroit Lions, 1953)", 
"X4cntkPpB4w+Top 10 Special Teams Plays - 2022 Season | Detroit Lions", 
"nqLI1suuuzU+Fordham LB Makes 31 Tackles in ONE GAME | 2021 College Football", 
"LJYf364NaYo+Larry Csonka Highlights", 
"DHX-obVmY5I+Larry Csonka power football running back", 
"leWB6BOTrww+Larry Csonka Highlights", 
"cf2Zp5FppcQ+Curley culp highlights", 
"BwNRv76GB1s+Tribute video to NFL Hall of Famer, Curly Culp who played with Chiefs and Oilers. Rest in Peace", 
"ESqEMLrN7S0+Curley Culp | Titans Oilers Week", 
"qh6ZfZS8bWQ+Remembering Hall of Famer Curley Culp", 
"5fwcwHeI87U+Curley Culp: Football Defensive Tackle", 
"por6HOxPrXA+A Football Life Al Davis", 
"tS51dC5y8tc+Al Davis and the Raiders: Time", 
"V8rM9pYu3MQ+Terrell Davis Career Highlights", 
"HckP7R92_L8+Terrell Davis 1998 Highlights", 
"yy-lnbMfhNg+Terrell Davis Rushes for 2000 Yards In a Single Season | A Football Life | NFL Network", 
"hfbrB9XQSu4+Willie Davis homers off Ryan in 6th for NL in '73 ASG", 
"TSJw0qtlEVA+Willie Davis 2022 playoffs highlights Year 2", 
"PkZbGB4lfrU+Brian Dawkins' Top Play from Every Season | NFL Highlights", 
"dKjsAGZZJ6s+Dermontti Dawson Mix| “Wish Time Would Stop!", 
"tc1SjY0ANPc+Dermontti Dawson's Pro Football Hall of Fame Induction Speech from 2012 | Pittsburgh Steelers", 
"WYl6XNjX9Bo+Ray Lewis talks battles w/ Steelers HOF C Dermontti Dawson", 
"msx1GTOr4vI+What it Takes: Dermontti Dawson of the Pittsburgh Steelers", 
"-8f7plX0VXY+Len Dawson Highlights", 
"n0msKLvTIxM+Remembering Chiefs Legend and Kansas City Icon, Len Dawson | Kansas City Chiefs", 
"7HfKbsWKEdk+Lenny The Cool - Len Dawson Career Highlights", 
"lUSpOsf5384+Chiefs Honor Len Dawson’s Choir Huddle On 1st Play Vs Packers Preseason 2022", 
"kEn_mrtrWk0+Fred Dean 49ers Best Highlights", 
"8bsv6EYFeSI+Every Fred Dean Sack (Playoffs: 49ers) | Fred Dean Highlights", 
"aMRunIaa7wo+Fred Dean Tribute", 
"irxb8ckmyp4+Fred Dean Highlights | How a 49ers Fan ENDED a Holdout & Helped His Team WIN Super Bowl XIX", 
"pfOqzMSanPo+Fred Dean arrives", 
"gEi3pn2L1go+FRED DEAN HAMMERS JOE THEISMANN", 
"jyB-rEtoJ6A+Best of Edward DeBartolo's Hall of Fame Speech", 
"RTOc_lyN5Ic+Ed DeBartolo Junior’s influence in Youngstown", 
"9KwMANROJwc+49ers Alumni Share Their Memories of Eddie D.", 
"QZ9sX5gpaxU+Joe DeLamielleure", 
"67bDApg-F5U+Joe DeLamielleure on Jets Legend Joe Klecko", 
"AmzFKjDDNac+Joe DeLamielleure Untold Stories and Favorite Memories as a Buffalo Bill", 
"O5Acq7nDwyc+Joe DeLamielleure On Joe Klecko's Hall Of Fame Case: \"He Dominated At Three Positions\"", 
"bzdx12DYV_4+Hall of Famer Joe DeLamielleure Recalls the Kardiac Kids | Browns Club 46", 
"KtMBXIA76RE+Richard Dent Ultimate NFL Career Highlights", 
"L-HleSORQzA+Richard Dent: The Best of the Best", 
"QLw5hRf0_Zo+1988 - Richard Dent Jumps over 49er's Lineman to Sack Montana", 
"Bi1YALBcoFw+Eric Dickerson - Greatest RB of all time", 
"4uv-cafaY4o+ERIC DICKERSON EVERY 20+ YARD NFL TOUCHDOWN", 
"zunI03VKGQc+1983 St. Louis Football Cardinals: Dan Dierdorf's last play", 
"uS1re_3_cbw+Dan Dierdorf Highlight Video", 
"PzYKGNJeBOA+Dan Dierdorf Highlights", 
"wheTogztk0A+NFL - Special - The Nastiest Man In Pro Football - Cardinals Conrad Dobler imasportsphile.com", 
"CPPMeEKBvA0+Bobby Dillon selected to Pro Football Hall of Fame Centennial Class", 
"uhzBI7bQLko+#4 Mike Ditka | Top 10 Tight Ends of All Time | NFL", 
"X0XUWE0_J7Q+Mike Ditka Rants (Includes \"Ditkith\")", 
"rxBhPEQXQdk+(1080 HD) Chris Doleman || NFL Career Highlights", 
"CP8c7xf_0Pk+Chris Doleman Highlights", 
"DzgM0YSdMK8+Chris Doleman || Legends || Career Highlights (RIP)", 
"LPr5QGGlE2w+Art Donovan On His Dirty Style Of Football | Letterman", 
"oJkHg9OovxE+NFL   1958   Special   Baltimore Colts Defensive Line   Big Daddy Lipscomb + Art Donovan + Don Joyce", 
"VqBB9xdGPEc+NFL - Special - Men Who Played The Game - Baltimore Colts DT Art Donovan imasportsphile.com", 
"U9cRWKaeFNY+Art Donovan", 
"7HDRLnoAY9E+Art Donovan on The Tonight Show", 
"17XPuE9ASPI+EVERY Tony Dorsett Touchdown as a Dallas Cowboy", 
"a0tP6m2fmfg+TONY DORSETT'S BRUTAL END AS A DALLAS COWBOY!", 
"Mv70EsRksrE+When Football Was Football - NFL's First Superstar: John \"Paddy\" Driscoll", 
"LKMbn1YsTQk+Sports' Forgotten Heroes - Paddy Driscoll - NFL", 
"ycpKSTnpeVo+Keith Wood punch clatters Gary Teichmann's jaw", 
"1I-_wx1IXZU+This is why O’Driscoll is the greatest 13 ever", 
"OHI2UjzXqhg+Football Feature - Bill Dudley", 
"EQo4XSg2D_8+Blessed Trinity Head Coach Ed Dudley Talks Top 10 Matchup & Top Plays From Last Week", 
"NYqr3qUID40+Top Rookie Plays from Week 1 | NFL Highlights 2023", 
"Y0gwkXXwM-M+#9 Tony Dungy: Countdown to Gopher Football 2013", 
"e1WbTfd1dpQ+Tony Dungy describes playing with OJ Simpson on the 49ers | EPISODE 14 | CLUB SHAY SHAY", 
"R12_XYAAVho+Tony Dungy Colts Defensive Back Play part 1", 
"gu9DjOu4W64+Tony Dungy, Minnesota Vikings, Defensive Back Play", 
"lrWelo5geWw+Legends Throwback: Kenny Easley | 2020 Seattle Seahawks", 
"a-jVcpb-0pE+The Enforcer | Kenny Easley | The Craziest Moments In Seahawks History", 
"FnI-i_C0sGE+Kenny Easley \"Your Soul\" || Career Highlights", 
"8uXFJ_Zy0Fw+Turk Edwards: Hall of Fame Football Tackle", 
"sPTuYVqQPGM+What position did Glen \"Turk\" Edwards play?", 
"D24gbvqomOA+Who did Glen \"Turk\" Edwards play for?", 
"8uSJP5sG5eU+When was Glen \"Turk\" Edwards inducted into the College Football Hall of Fame?", 
"R42nQdAtUF4+Carl Eller Vikings Highlights", 
"vFg6ub8bo6g+Carl Eller", 
"MU7jKjmBQl0+Minnesota Vikings • Carl Eller", 
"-5pb4UKO9uw+Hall of Fame player Carl Eller talks Bud Grant legacy and friendship", 
"mxk2RwyJ8F8+THE ULTIMATE JOHN ELWAY HIGHLIGHT REEL", 
"2f4wN7N3_oA+Weeb Ewbank - Jets HC 1963-74 HD", 
"VNRejCsxW3I+Top Plays from Week 1 | NFL 2023 Highlights", 
"86kW3wSoYTc+Weeb Ewbank Top # 12 Facts", 
"pZ__70-XfaU+Weeb Ewbank", 
"gg7IzIdpVTw+Legends Series: Alan Faneca", 
"Npgur4-oAzo+Alan Faneca makes the greatest block in Super Bowl History", 
"dZy6fb7ETF8+Alan Faneca Full Hall of Fame Speech | 2021 Pro Football Hall of Fame | NFL", 
"qYFAgjwVlK4+NFL Great Alan Faneca Talks about Playing Offensive Line and Reaching the Pro Football Hall of Fame", 
"L7P_fy7kEuI+Marshall Faulk Highlights - High Quality from 'A Football Life'", 
"wdG0T0lMpvc+Marshall Faulk's Incredible Touchdown Run (Browns vs Rams 1999)", 
"XkaEG1bSDPI+Classic Tailback - Marshall Faulk San Diego State Highlights", 
"KFbkprL05Y0+Brett Favre: The Greatest Gunslinger of All-Time | NFL Legends Highlights", 
"amZgGGhK8cE+Brett Favre Throwing Bullets for 2 minutes and 20 seconds", 
"TfrEOJHOfhk+Los Angeles Rams Tom Fears 🤘", 
"PRiVlx6eu1w+Tom Fears", 
"E37dw600JQ4+Tom Fears: Hall of Fame Football Split End", 
"sUGEAJ2_x00+Ollie Matson #33 Tom Fears #55 Merlin Olsen #74 Dick Butkus #51 Football Rams Linemen Hall of Famers", 
"iMU5eQFEcRg+ICONOS DEL DEPORTE  TOM FEARS", 
"RHj3q-9DD8w+Jim Finks Hall of Fame Football Quarterback", 
"qyyFWZIh3PU+JOHNNY UNITAS CUT BY PITTSBURGH STEELERS IN 1955; JIM FINKS, ANOTHER HALL OF FAMER, EXPLAINS", 
"VNRejCsxW3I+Top Plays from Week 1 | NFL 2023 Highlights", 
"9cqsIedJew4+Jim Brown's Top 5 Runs", 
"PX_FDqkdm5k+NFL - Special - Men Who Played The Game - Washington Redskins RB Ray Flaherty imasportsphile.com", 
"gyvyBI7nRJg+Ray Flaherty: Hall of Fame Football End", 
"7akvkvqbOok+Flaherty's stop starts great double play", 
"a1QVJTu8Qbo+The GREATEST Offensive Duos Of All Time", 
"tTGe2SU0h4A+Tom Flores and Carlos Santana Catch Up on the Silver and Black, Music and More | Las Vegas Raiders", 
"s6b2a36tTYI+John Madden, Tom Flores, Jim Plunkett & Cedric Hartman at Super Bowl XV (January 23, 1981)", 
"L-BBqSiYnzQ+Len Ford: Hall of Fame Football Defensive End", 
"F6V9yhWarP4+Len Bias Maryland Highlights", 
"wEukBbISYeQ+Horacio the handsnake - Len Ford", 
"PMWQUuyj9EU+Dan Fortmann: Hall of Fame Football Offensive Lineman", 
"1wW6eLb-pRQ+Every Team's Top 10 Plays of All Time!", 
"j3EBHlYqass+The 5 Best Passing Plays in Madden 24", 
"02mhqOF0oi8+The Fake Spike: Dan Marino (1994)", 
"zY3yuUUHyTQ+Dan Fouts Lights Up Dolphins with 380yds 4 TDs | LA Chargers", 
"TECLPBk1IlY+Dan Fouts Legendary Performance At Epic In Miami | LA Chargers", 
"iPUcsLRX4pA+MFIC: Dan Fouts", 
"fxfv5IWxjEs+Benny Friedman's BEST Music Videos | TOP 10", 
"v6rtV3CwCQ4+Frank Gore's Career Highlights in Red and Gold | 49ers", 
"8bBJa2dv5vY+Frank Clark's Top 10 Plays from the 2020 Season | Kansas City Chiefs", 
"8GaKpVJxqtM+Frank Gore \"The Tank\" Career Highlights", 
"hJsuQzoIDf4+1992 Houston Oilers Team Season Highlights \"The Greatest Show On Turf\"", 
"qWrwOrjIkS4+Frank Thomas | Career Highlights", 
"Xpe90T6_Dwk+Bill George: Leaders Need High Emotional IQ to Succeed", 
"aUbH7GbQm4Y+Paul George Top 10 Plays of Career", 
"4xnnHQJrvSA+10 Minutes Of Paul George Being Better Than You At Basketball 🤷‍♂️", 
"q0SzDPKOuUA+Paul George Isolation Scoring Highlights", 
"9jFY6Tujur8+Best of NASCAR: Joe Gibbs Racing's' biggest moments", 
"7kxGlHN0DjI+25 Times Joe Gibbs Racing CHEATED", 
"FrJPHReDll8+The GREATEST Loss of Joe Gibbs' CAREER | Redskins @ Cowboys (1990)", 
"Zlqdle4cBXI+The Most Underrated Coach in NFL History.", 
"Z2OZFvnEKNc+The STRANGEST MOMENT of Joe Gibbs' CAREER | Redskins @ Steelers (1991)", 
"8Pw7wTAwMO8+Frank Gifford Highlights", 
"W-PCYGvloxc+Chuck Bednarik hit on Frank Gifford | NFL 100 Greatest Plays - No. 44", 
"o1EHius5Y88+Chuk BEDNARIK plaquage Frank Grifford", 
"F6nHXBvUl_Q+Sid Gillman", 
"0amEu3GJPEo+Sid Gillman", 
"QFv9ONl5HeA+The Father of the Forward Pass | Sid Gillman Coaching Tree", 
"y44IVKOmHd4+The CONTROVERSY Between Sid Gillman and John Hadl | 1966 Chargers", 
"nCDZV4sIEEU+#16: Otto Graham | The Top 100: NFL's Greatest Players (2010) | NFL Films", 
"Kdcw6-nAAGI+The Forgotten Dominance of Otto Graham", 
"Z9Bx-3Vk6MU+Paying Tribute to Minnesota Vikings Legendary Head Coach Bud Grant", 
"6NoB54Ycsoo+Bud Grant goes ballistic", 
"pnlBrtB-ASw+Darrell Green Career Highlights", 
"cO6TEmjO5Uw+DARRELL GREEN GREATEST CHASE DOWNS", 
"LgOdfPyFjts+Darrell Green: Football's Peter Pan | NFL Films Presents", 
"lifNhRpEh48+#13: Joe Greene | The Top 100: NFL's Greatest Players (2010) | #FlashbackFridays", 
"cLcJkiFh5ec+'Mean' Joe Greene: A Football Life - Creating a Steelers Dynasty", 
"Ysc6fkyAvaM+Joe Greene doesn't give a shit", 
"u2WuUM3-CvA+Linebacker Kevin Greene “The Mean Machine” Career Highlights", 
"qNm7Qip-_ZQ+Kevin Greene's UNBELIEVABLE 1994 Season Highlights | 14 SACKS!", 
"EikdXxfUVfQ+Every Kevin Greene Safety | Kevin Greene Highlights", 
"HSeuLk7eGGM+Every Kevin Greene Touchdown | Kevin Greene Highlights", 
"-x1CfKDQ1B8+Rugby Player Reacts to FORREST GREGG #54 The Top 100 NFL's Greatest Players!", 
"sf2n7R8tbNI+Forrest Gregg's battle", 
"JXi-UOUm2R8+The WORST Moment of Forrest Gregg's Career | 1977 Browns", 
"Q_5hi2Tyvgg+BOB GRIESE (THE QUARTERBACK WORE GLASSES) TRIBUTE", 
"cqOh4Zq0RDc+Russ Grimm HOF Tribute", 
"TPpczBRPgp4+Russ Grimm on Offensive Lineman", 
"XiILkM-IrXU+\"The Hogs\" Ultimate NFL Career Highlights || 1980s Redskins Offensive Line", 
"POdGfMTuTF0+Russ Grimm   Power, Counter 1", 
"5j1dFuO-VKs+Russ Grimm and Tank Tantlinger Joe Moore Offensive Line Camp 2023", 
"uh0lu99eG70+The MOMENT That SAVED Lou Groza's CAREER | 1964 Browns", 
"TctzBrKl7Bc+1961 Week 2: St. Louis Cardinals at Cleveland Browns Highlights", 
"cyBozdPrIq4+Browns History: Lou Groza signed his contract in Okinawa | Cleveland Browns", 
"P_NY-QSOfXs+College Football Best Plays of Week 2 | 2023-24 ᴴᴰ", 
"wdoCFAJGMR8+Ray Guy Highlights - Greatest Punter Ever", 
"1eE7zLf257I+The CRAZIEST STORY of Ray Guy's CAREER", 
"ogdeHzBi4YM+Ray Guy", 
"tvKJoxOXdPQ+Joe Guyon: Hall of Fame Football Tackle and Halfback", 
"HHmpST7sm4k+HAVE GRAVE, WILL TRAVEL: PAUL HORNUNG & JOE GUYON", 
"P_NY-QSOfXs+College Football Best Plays of Week 2 | 2023-24 ᴴᴰ", 
"Wy3twFMqZVg+Joe Mixon's Top 10 Plays", 
"Cu833XcGhtM+George Halas - Sportscentury", 
"P0IqRwEIcko+George Halas", 
"TIRyiO8N330+George Halas - Hall of Fame Induction Documentary", 
"ta-eiffqfCA+Papa Bear George Halas HD", 
"LozADrv-RBg+The Legend of George Halas", 
"q663VaPoNFk+Charles Haley 49ers Best Highlights", 
"hcreRFB8x5c+Charles Haley Highlights", 
"cZRnKbUZd8A+Linebacker Jack Ham “The Hammer”", 
"4xxnv49TKxI+Dan Hampton Ultimate NFL Career Highlights", 
"c8vktn3XncM+Dan Hampton HD", 
"QNsftkM1ZbY+Dan Hampton - Hall of Fame Documentary", 
"YOY7ZtBB0tE+danhampton trackID", 
"fl3aBCRaVDM+CHRIS HANBURGER \"THE HANGMAN\" WASHINGTON REDSKINS LB 1965-1978", 
"AsNPY-vlsB0+Chris Hanburger: Hall of Fame Football Linebacker", 
"ueDmib9zSYE+Top 80ish All-Time Redskins-1973 Topps Chris Hanburger PSA 8!", 
"DKdi-R_rOB8+Chris Hanburger - 2011 Pro Football Hall of Fame Presentation and Speech (8-5-2011)", 
"_Lq33EZ8gJY+The Chris Hanburger HOF TTM Autograph \"Player Era\" Project", 
"-ltiyQwDaJk+Pro Football Hall Of Fame Disrespect Of Chris Hanburger", 
"STdtQL6xzuY+John Hannah Ultimate NFL Career Highlights", 
"V4JAjAUt5T0+John Hannah Highlights", 
"VTiUPC4eXPY+Where Are They Now with John Hannah (2022) - Patriots Alumni", 
"GjMBcdFZUUk+Cliff Harris Dallas Cowboys Highlights", 
"B4SOgWC49R8+Cliff Harris- The Boogeyman: Analyzing The mind of a Football Monster.", 
"mRVQRnbl6mY+Jack Lambert Slams Cliff Harris (Cowboys vs. Steelers 1976)", 
"csUy44Uk7D0+Franc The Italian Tank - Franco Harris Career Highlights", 
"vjE7qcf87rg+NFL Films Looks Back on the Career of Franco Harris", 
"hkSHeJJnW0Q+Franco Harris Highlights", 
"EmY6doDP-zc+Marvin Harrison - {Career Highlights} The Quiet Storm (pt. 1)", 
"fOFRlz7wJL0+Bob Hayes Career Highlights", 
"pzYdzcs_nfs+Bob Hayes Highlights", 
"mzhUkrSSmM0+\"BULLET\" BOB HAYES EVERY 50+ YARD NFL TOUCHDOWN", 
"3KbrlxrCbk8+How fast was Bob Hayes?", 
"eCeZdJUaxOs+Mike Haynes Highlights", 
"E7ScioNYWs0+Mike Haynes: 'Top 10' In Season Trades", 
"xxyFKD-M9-w+Ed Reed Top 50 Most Dynamic Plays!", 
"GQrZKveWgOk+Bill Belichick praises Ed Reed \"Best play I have seen a free safety make'", 
"WqESGc1AnqU+One of the best guitarists ever: Jeff Healey", 
"eJRmh68KGrE+All 70 of Ed Reed's Ravens Interceptions | Baltimore Ravens", 
"OH5DHS9WoBQ+A TWO-MINUTE MUSING: Mel Hein", 
"17qorlr2Gmo+Mel Hein: Hall of Fame Football Center and Linebacker", 
"yb2l6N4lbbo+Rugby Player Reacts to MEL HEIN #96 The Top 100 NFL's Greatest Players!", 
"j3EBHlYqass+The 5 Best Passing Plays in Madden 24", 
"jL9nF9aP2Mo+Ted Hendricks Highlights", 
"ccOPaYjmL7U+80 Raiders Ted Hendricks HD", 
"Gk664aImJjo+Derrick Henry Top 10 Career Plays", 
"02pjwTxFsKQ+The Football History Dude - Wilbur “Pete” Henry – Bigger Than the Founding of the NFL", 
"l9WGkBwr6sA+Derrick Henry's Top 10 Longest Plays... So Far", 
"efM_JbJiwnQ+MLB Hottest Moments", 
"fn7p8lmf_GY+The Arnie Herber Story", 
"7KsiJ26Rj9I+Green Bay Packers vs. Boston Redskins1936", 
"TQ3nOyiL0Mg+Packers' Arnie Herber Honored", 
"r03LekPmEt0+9PM FRI ARNIE HERBER RECEIVES HOMETOWN AWARD", 
"SC24HZyNn_4+Bill Hewitt: Hall of Fame Football End", 
"0yLcorErL0M+Horacio the handsnake - Bill Hewitt (football player)", 
"F7_nWEqJ3Uk+Lleyton Hewitt: Best Ever ATP Shots & Rallies", 
"VD1vxyBWjVA+Gene Hickerson: Hall of Fame Football Offensive Guard", 
"jyFHICRIMS8+Cleveland Browns - Gene Hickerson Leads Greg Pruitt", 
"NObmG2RDjwg+Gene Hickerson HOF Induction video", 
"SBi9Dn641gc+Gene Hickerson Hall of Fame Introduction.", 
"44r0usP0DPg+Browns Hall of Famer Gene Hickerson dies at 73", 
"q1O58lJ8duA+Tyreek Hill Top Plays of the 2022 Season", 
"B3gaVrXlacw+Taysom Hill's Top Plays 2022 NFL Season | New Orleans Saints", 
"wNjn7trpiJE+LOCAL BOXING | Winston Hill dedicates win to family", 
"XU1HX-bGV7g+College Football Top 100 Plays of the 2022-23 Season ᴴᴰ", 
"VNRejCsxW3I+Top Plays from Week 1 | NFL 2023 Highlights", 
"v-gGIzHwcKA+Highlights: Rams' Top Plays vs. Packers In Week 15 | Tyler Higbee TD, Leonard Floyd Sacks & More", 
"IMlecoDvg6E+Paul Hornung Highlights", 
"ACbEAjKDTlM+The Golden Boy - Paul Hornung Career Highlights", 
"O-5Dldf6nIo+Paul Hornung MVP - Career Highlights (Casino Lights Remix)", 
"QcVpozSTgWs+Every Paul Hornung Touchdown (Receiving- 1966) | Paul Hornung Highlights", 
"0xzI6BFH-fI+Redskins Top Plays: Ken Houston's Big Stop 10/8/1973", 
"NwfC9IlvJpw+Ken Houston Highlights", 
"R5pdTb1H6zA+KEN HOUSTON NFL ULTIMATE SAFETY - HOUSTON OILER YEARS 1967 - 1972 (PRO FOOTBALL HOF CLASS OF 1986)", 
"hOSMMmBQv9M+Ken Houston: Redskins Legacy | HTTR4LIFE", 
"zKR2VW9McYY+KEN HOUSTON - HOUSTON OILERS - 2 INT RETURNS FOR 2 TDS IN 1 GAME (DEC. 19, 1971) (6th NFL PLAYER)", 
"m6GKkG3PKk8+CHUCK HOWLEY: HOW GOOD WAS HE REALLY?", 
"2RK_vLQZgG0+Chuck Howley Highlights", 
"rEtuulUvgxU+Former Mountaineer & NFL Great Chuck Howley - NFL Highlights", 
"ghaK7gG-FHQ+Howley Fame: Deep Blue | Dallas Cowboys 2023", 
"UdvXhb2hdvY+The Knock: Pro Football Hall of Fame Class of 2023 member Chuck Howley learns of his election", 
"avTIAIAzpuk+The turf monster gets Chuck Howley - Super Bowl VI", 
"brOuEaNAV_8+NFL All-Time Team: Cal Hubbard", 
"RE9h9yqYu4s+Cal Hubbard hall of fame", 
"bLe2yOao9MA+The Football History Dude - Robert Cal Hubbard – Hall of Fame Tackle (Packers / Giants / Steelers)", 
"rUHQcj_Knvk+💦 Top 6 Quotes of Cal Hubbard - Football player", 
"xQRXKef19qE+Robert Cal Hubbard – Hall of Fame Tackle (Packers / Giants / Steelers)", 
"SUzefTm_PzY+Sam Huff 2022 Highlights", 
"mblTVdOfjPE+#WVU125: Sam Huff NFL Highlights", 
"HjG4uEcI124+Sam Huff: Redskins Legacy | Throwback Thursday - HTTR4LIFE", 
"9lcvnVaAEjw+[Double-A Frisco] Sam Huff's 500-foot Home Runs in 2021 (so far)", 
"1C-Yl_YA4m4+PHILADELPHIA EAGLES CLAUDE HUMPHREY Highlights 🦅🏆", 
"IeMg-tmh_2M+Remembering Hall of Famer Claude Humphrey", 
"iOD7s7azEMM+Draft Day: Claude Humphrey", 
"KXm_oS4ouco+Claude Humphrey Hall of Fame", 
"4Sw3YLh4LAY+2023 Lamar Hunt US Open Cup Semifinal: FC Cincinnati vs Inter Miami - Highlights - Aug 23", 
"mzGPVsEzIAY+2023 Lamar Hunt U.S. Open Cup: Orange County SC vs. Capo FC - Highlights - April 5, 2023", 
"hxRRRMsDn_A+Lamar Jackson Top Plays of the 2022 Regular Season", 
"g2Bw5uephUM+Orlando City's Journey to the 2022 Lamar Hunt U.S. Open Cup Final", 
"nW83xbIVzB8+Steve Hutchinson's Best Blocks As A Seahawk | Seahawks Video Vault", 
"uRuPr-_owgU+Seattle Seahawks guard Steve Hutchinson highlights", 
"kkjgxhQXZ6U+Vikings Circle: Steve Hutchinson | Minnesota Vikings", 
"TANvdvQZB48+Don Hutson 1930s & 40s Highlights | Throwback Month!", 
"v6qtqkLdZek+Don Hutson - Poetry in motion", 
"BU4bzn4ge-I+Michael Irvin Top 25 Plays!", 
"60V0aJ_mTSc+Michael Irvin NFL Career Highlights | Dallas Cowboys", 
"5xuXPUGJGuU+The Dome Patrol: The Best Linebacker Corps in NFL History", 
"k9VerWNHc8U+Rickey Jackson Highlights", 
"SbIqSZFWWJI+Saints History: 101 \"Rickey Jackson\"", 
"dOR7IDDfLm4+Greatest Plays of Edgerrin James' Hall of Fame Career | Colts Top 10", 
"AXxkgI5r6mo+Edgerrin James Career Colts Highlights | Hall of Fame Class of 2020", 
"s-5MoyVNXwQ+Edgerrin James - The Edge (Career Highlights) pt. 1", 
"egahq0Br9XE+Classic Tailback - Edgerrin James Miami Highlights", 
"Ksp9Gd7dlQA+Top 5 moments of Jimmie Johnson's NASCAR career | NASCAR on FOX HIGHLIGHTS", 
"yBxglpdjZ20+Jimmie Johnson's biggest and best career moments : Best of NASCAR", 
"tlQKTF8b7wQ+Jimmie Johnson’s Best Saves and Near Misses", 
"CAjicK3Z9e8+Best Of Jimmie Johnson NASCAR Radioactive", 
"Ys6u9yKKDfk+Jimmie's Texas dominance | Best of Jimmie Johnson and Texas  Motor Speedway | Best of NASCAR", 
"3oBKZ5FAHgU+Six minutes of 'Seven-Time': Watch Jimmie Johnson's career unfold", 
"L7e1fyBY9Vk+John Henry Johnson Highlights", 
"0su-yorApHo+John Henry Johnson Highlight Segment | NFL Highlights HD", 
"HLZ9iSTTbTY+Juwan Johnson's Top Plays 2022 NFL Season | New Orleans Saints", 
"hUiQbsAywyM+John Henry Johnson: Hall of Fame Football Fullback and Halfback", 
"o8pXifXkncw+10 years of Guitar Playing, in 3 minutes! - John Henry Johnson", 
"ClsT7b47Q7Y+Charlie Joiner Career Highlights", 
"c1Ee2l5oyR0+Charlie Joiner", 
"qtgsGWy_cJo+Charlie Joiner", 
"2z69rFSA5HU+1980 - Charlie Joiner Hit Hard By Steve Wilson", 
"QvrZ3CgqQV4+NFL Hall Of Famer - Charlie Joiner", 
"81DlLKZzc64+Deacon Jones Highlights", 
"oroYiMgSaXI+Deacon Jones Highlights", 
"_qvOyzJQY7k+Deacon Jones: The Best Pass Rusher EVER?", 
"f_qOYZ8KSZw+NFL Films Remembers Deacon Jones", 
"aLp4hp1RsaE+Jerry Jeudy's top plays of the 2022 season", 
"XDiKz8FiE1E+The Top 5 Reasons You Can't Blame...Jerry Jones (2006)", 
"44gY8ID8m9I+Jerry Jones and the Dallas Cowboys", 
"a2HRa6Q9mCU+Jerry Jones Grades McCarthy's Play Calling, Talks Dak Criticisms, And More | Shan & RJ", 
"icO_TS4DK_4+Winning the Situation Game with FSU's Stan Jones!", 
"mO8I8Vuryyw+Marcus Jones Top Plays of the 2022 Regular Season", 
"Ka90ERKLTJQ+Ghost Riders in the Sky - Original - Stan Jones (1948) *HD*", 
"8U8LvQ8xB3Q+Stan Jones: Hall of Fame Football Guard and Tackle", 
"xrzsk1FYTww+Walter Jones Ultimate NFL Career Highlights", 
"bUj7ccvbpFc+The Block | Walter Jones | The Craziest Moments In Seahawks History", 
"nRYik8wz7wQ+Former NFL Player Describes the Impossible Challenge of Going up Against Hall of Famer Walter Jones", 
"jbW4f60dCNA+Michael Jordan’s Top 60 Career Plays", 
"l-acLhyuhpk+Sonny Jurgensen Highlights (Final Version)", 
"I0m8KZfctwU+tom brady Sonny Jurgensen: THE PassMaster--Lombardi said\"He's the Best I've Ever Seen!\"", 
"tlPzthn9lyo+PHILADELPHIA EAGLES SONNY JURGENSEN Highlights 🦅🏆", 
"GZ4ZMdzrQ_o+Before he played Mongo, Alex Karras played football", 
"fTDCAI6lhy8+Alex Karras Junior Year Highlights", 
"C46-vtA3A60+Jim Kelly Highlights", 
"56JJ9MOaFgU+JIM KELLY 10 LONGEST NFL TD PASSES & MORE (PRO FOOTBALL HOF CLASS OF 2002) (MIAMI)", 
"4f5R9oQjjXc+Leroy Kelly Highlights (Final Version)", 
"jRxOPIeJYuo+Leroy Kelly Highlights (1964-1973)", 
"Y09JgwuMsHM+1969 NFL Pro Bowl-Game highlights-Roman Gabriel and Leroy Kelly", 
"0x_SHjHPTZA+LEROY KELLY, Black College Football Hall of Fame", 
"jcxNb1opMUs+Leroy Kelly discusses taking over after Jim Brown's retirement | Browns Club 46", 
"p6paGy6Zb8U+The Unstoppable Man | Cortez Kennedy | The Craziest Moments In Seahawks History", 
"RTycAlWhrt8+Cortez Kennedy's Hall of Fame Career Remembered | NFL Films", 
"Prsu-OsPuZ4+Steelers Hall of Famers: Walt Kiesling", 
"bN9fBaQy1Qg+ESPN's Top Ten NFL Plays of the Past 25 Years", 
"ywjbVbEBvDg+Kenny Pickett Top Plays of the 2022 Regular Season", 
"nWDr--D10Bs+Top HS football plays of Week 9", 
"0xzI6BFH-fI+Redskins Top Plays: Ken Houston's Big Stop 10/8/1973", 
"BoBHD4VxzzU+NFL 'ANGRY' Runs", 
"591ptQIUTgI+Top Plays: Clayton Thorson Highlights vs. Notre Dame Fighting Irish | Big Ten Football", 
"MzI4eEqnGqE+Karan Higdon - Top Plays (Until Rutgers)", 
"ASl7FusECXo+The Mighty Mean Green Machine - Joe Klecko Career Highlights", 
"R408uWTBGE0+Joe Klecko: Worthy of a Hall Call", 
"lckipDnrCPY+Joe Klecko Highlights", 
"JPopwhyQqd0+Joe Klecko Highlights", 
"4S17q91FiVo+The best offensive block in history", 
"_kPMaInxIyM+Funniest Kramer Moments | Seinfeld", 
"ep_sTT1kvOk+Packers great Jerry Kramer on big games in cold weather.", 
"6PdGbFWt5Ps+PAUL KRAUSE NFL ALL-TIME INTERCEPTION KING (WASHINGTON REDSKINS YEARS 1964-1967) (IOWA)", 
"t5h0D7wj6qE+Paul Krause", 
"OlGGB_-Wf8U+Top 10 Safeties of All Time | NFL Films", 
"FFZ2_vR-1yQ+PAUL KRAUSE SETS NFL ALL-TIME INTERCEPTION RECORD - HANK STRAM GIVES CLASSIC ANALYSIS (DEC. 2, 1979)", 
"bnCDwKz9I8k+Paul Krause - Most NFL Interceptions of All Time", 
"vmn_ID9Mupk+Green Bay Packers, Curly Lambeau,  History", 
"IbcVRJ6gY_I+Two Minutes of Pro Football History: Leaders of the Pack", 
"xK2LyFBc_Yk+Green Bay Packers | In Wisconsin", 
"MRy-D45Yf_s+The First Lambeau Leap (Original Broadcast)", 
"YZxQ9HBjrX8+1919-1929 | Humble Beginnings", 
"ccoxfveqxaw+Linebacker Jack Lambert Ultimate Highlights", 
"6jvAylgmYkg+Tom Landry's BRILLIANT innovation of the Shotgun Spread REMASTERED!", 
"RH8zwjQTH10+TOM LANDRY: THE EVOLUTION OF THE 4-3", 
"AW5BnVygkfA+The CRAZY Story Behind Tom Landry's ONLY Touchdown Pass", 
"FMthqdOrGvI+Dick \"Night Train\" Lane Highlights", 
"Y8cdAJ78DZg+Night Train Lane🚂 The BEST Hitting Defensive Back Ever(Name A Better Hitter At Corner You Won't)💯🕦", 
"r-BjDyWoGlk+NFL's GREATEST CORNERBACK - DICK NIGHT TRAIN LANE -- FATHER OF THE FTP", 
"3yXwiMzkd1I+Dolphins Daily | Reviewing Jim Langer's career and Nike 11-ON event", 
"Dak63sb8wlE+Jim Langer: Hall of Fame Football Center and Offensive Guard", 
"tpNGEY7VZOY+Meet pro football hall of famer Jim Langer | South Dakota Almanac", 
"YJvCBKhHTEo+Miami Dolphins vs. Los Angeles Chargers | 2023 Week 1 Game Highlights", 
"mG8M7Ou1XBY+NFL Highlights 1972 Undefeated Miami Dolphins Season - imasportsphile", 
"IpNgf1X7eHs+Willie Lanier Legend Highlights", 
"qYGoDlfAxfI+Willie Lanier Kansas City Chiefs All Time Nuetralizer", 
"xSOPrwb-mQc+Football Feud: Steve Largent vs. Mike Harden | A Football Life | NFL", 
"EYDBu2jLbuw+The Greatest Revenge Moment in NFL History", 
"3A2csuEbsK0+Yale Lary Highlights", 
"yngiWV-634Y+Yale Lary ● A Simple Tribute", 
"tofo9KxJwpY+Yale Lary", 
"YR3IxXyXn68+Century Club Impact Moment - Yale Lary '52", 
"9ab2cskK6SI+Lions Hall of Famer Yale Lary dies at 86", 
"YUF_bcSUzJk+DeAndre Hopkins Top 10 Career Plays", 
"MjgO6il5mwo+GameDay's Great Eight Top Plays - Week 1", 
"xMTx3xynd2M+Dilettante Ball 183 - Dante Lavelli", 
"iJQ6jw309W8+Ty Law - The Long Arm of the Law ( Career Highlights) {vol. 1}", 
"da560iHuvDc+Best of Ty Law | Patriot Hall of Famer | Career Highlights", 
"Nn5iMi2a-To+Bobby Layne Highlights", 
"AAuj_GXmyxo+Two minutes of pro football history: Creating a Layne", 
"aX4eTvPKuOI+The Curse Of Bobby Layne", 
"MVeGfH1c8xU+Dick LeBeau - Defensive Guru", 
"hSfC51F1qtA+The Pittsburgh Steelers (Dick Lebeau and his defense)", 
"AqPzmmP6A6s+Dick LeBeau details what made Steelers 2000s defenses so LEGENDARY", 
"TBsyLo6HPS4+Tuffy Leemans: Hall of Fame Football Fullback,  Halfback, and Quarterback", 
"J73YEKR7urY+Horacio the handsnake - Alphonse \"Tuffy\" Leemans", 
"ny95QZm4mRQ+Pro Football Championship game 1941", 
"Qgimx4unvhI+2017 Tuffy Leeman Awards Ceremony #2", 
"95nzAycn8sM+2017 Tuffy Leeman Awards Ceremony", 
"TbnTuE_Om5Y+Marv Levy quotes: Buffalo Bills legend’s greatest Marv-isms", 
"vxeYZOQODig+Marv Levy: \"Ageless Wonder\"", 
"GedyL5penhA+Jim Kelly, Marv Levy Lead Pregame Chant Before Home Opener | Buffalo Bills", 
"lp_roR7Zq_M+Marv Levy: Master Communicator", 
"gvPWK9vzgwU+Where Else Would You Rather Be? | Kickoff to the Buffalo Bills' 60th Season", 
"DEKXWNey_Wc+Ray Lewis' INSANE Career Highlights | NFL Legends Highlights", 
"sbu6xDxOfPc+Bob Lilly “Mr Cowboy” highlights", 
"ga0VnGSgnUY+Bob Lilly", 
"063FENiAYdU+Bob Lilly, Dallas Cowboys DT (1961-1974)", 
"hk7eZbO7SyI+Floyd Little Highlights", 
"BA3GY21fV44+Floyd Little: The Franchise", 
"Ayg07Y4khQY+Every Floyd Little Touchdown (1970) | Floyd Little Highlights", 
"Kl4umfv7B2k+Floyd Little: Syracuse University top sports figures of all time", 
"mtGhX_lPttU+Larry Little's most memorable games", 
"_eiIHaOGh5U+Larry Fitzgerald: Best Hands in NFL History Career Highlights! | NFL Legends", 
"EcQKvJER8Vs+Larry Bird Highlights | Part 1 | Boston Celtics | NBC Sports Boston", 
"Rr4eJAlMoCY+James lofton(KING OF BIG PLAY)career highlights part 1", 
"-EapvtHLxB0+James Lofton", 
"UnxmtscdbmI+James lofton (KING OF BIG PLAY) career highlights part 2", 
"DTlrdczjjOA+James Lofton 1986 SuperStars 0 5 Mile Race", 
"CTp32JRGZgM+James Lofton 25 yd TD December 23, 1989", 
"njlGLMYopLo+Vince Lombardi: The Coach Who Put Green Bay on the Map | A Football Life", 
"9zpPoruxy7k+The Sweep Run Play detailed by Coach Vince Lombardi", 
"uv4CXySXxCk+Vince Lombardi Teaches the Power Sweep Part 1", 
"0ylm1Qlx8sA+Howie Long: Iconic", 
"5Z9LtDi_Lbk+NFL - Great Players - Howie Long - Warlord Of The Raiders imasportsphile.com", 
"j4nPP9ox3uA+Ronnie Lott Highlights", 
"DtDED8KpIXA+The West Coast Reaper - Ronnie Lott Career Highlights", 
"oNabfHVX4Vs+#11: Ronnie Lott | The Top 100: NFL's Greatest Players (2010) | NFL Films", 
"0NOAR9xMFd8+Sid Luckman Highlights", 
"EoVlW02rq8Y+Roy Williams Greatest Hits", 
"UAHnQAbA08o+Link Lyman", 
"Iv7FwHMK7Ts+10 Dirtiest NFL Players of All Time", 
"FP-RGz22NlU+The Chicago Bears Hall of Fame", 
"kRxpN5mRcRc+John Lynch || Tampa Bay Buccaneers Highlights || Buccaneer Throwbacks Episode 9", 
"CzDg-DDSat4+John Lynch - The  Lynch Mob (Career Highlights)", 
"yNwtkC7HIP4+John Lynch Career Highlights | \"Hitman 47\"", 
"f0TyG2uwTFk+Top 10 most feared tacklers - John lynch", 
"zvUqqJyyqXU+Tom Mack’s Offensive Line Legacy for 13 Seasons | Rams Legends", 
"13Y5_Q7JqEs+Tom Mack", 
"UkpYuwZBY8A+Tom Mack Classics Auction...SOLD to Joe for $1.00!", 
"rTSxVcU7DF0+John Mackey’s LEGENDARY highlights|| Underrated Colt 🏉||", 
"gL2gGdc6vQQ+John Mackey Legendary Broken Tackle - Voted #1", 
"gqgBenCQdvg+John Madden Best Calls", 
"2PQgMzgp8QI+John Madden's Greatest Moments & Calls - RIP", 
"QxrEESaTsCU+I Recreated the TOP PLAYS From NFL Week 1 in Madden!", 
"QWauhheNFTo+Peyton Manning's Most Iconic Moment vs. Every Team | NFL Highlights", 
"vuj9tzE2-U4+Tim Mara Football", 
"RNSomJOHdRI+Travis Kelce Top Plays of the 2022 Season", 
"eQov90lWgV4+Tennessee Titans vs. New Orleans Saints Game Highlights | NFL 2023 Week 1", 
"diEku6OCJXo+The Wellington Mara Tribute", 
"rHWbSBGlDsI+Wellington Mara 2000 NFC Championship game. NY Giants", 
"bieU5lN-nm8+Washington Redskins Vs New York Giants 10/30/2005", 
"8B7TC1wEAcM+WELLINGTON MARA HOF FINAL H264 Widescreen 1920x1080", 
"gVNAiUTxf2c+Gino Marchetti", 
"batgrW8euig+Gino Marchetti Tums-All Time Neutralizer", 
"H6O____gYKQ+Colt Gino Marchetti runs 33 yards for a touchdown in 1963", 
"5KPeUoW1Q6M+NFL - 1958 - NFL Films - The Baltimore Colts Defensive Front Four - The Most Colorful Of Them All", 
"wUoh29mk0Ws+Dan Marino's \"Quick Release\" Career Highlights! | NFL Legends", 
"5unrgfbiz_U+George Preston Marshall", 
"OhLGb0rWxkw+George Preston Marshall,Washington Redskins office,1940,Football,NFL", 
"-QX0X9M8f5E+Pigskin Dispatch - Who was George Preston Marshall?", 
"EbQbmRlyZSs+George Preston Marshall – Founder/Owner of Washington Redskins", 
"V8_uhIsHZWU+Statue Removed From Target Field Over Remarks Made In 1978", 
"Xt1BvCNUMHs+George Preston Marshall Statue Removed", 
"epVI2EdechI+Curtis Martin - New York Jets Highlights {My Favorite Martin!!}", 
"-RX-WrdKQW0+Curtis Martin - New England Patriots Highlights {My Favorite Martin!!}", 
"IFGGCwR7U6s+Curtis Martin's 2 TD, 134-YD Day vs. Seahawks in 2004 | NFL Throwback | The New York Jets | NFL", 
"c3Qi2oLqNDI+Highlights of NFL Hall of Famer Curtis Martin First Game...from the 1st to the Final carry...", 
"596YaZQN6JY+Ollie Matson Highlights", 
"TAlLh0Q06YA+PHILADELPHIA EAGLES OLLIE MATSON Highlights 🦅", 
"JBHCh7CAx_o+Nfl Ollie matson", 
"t8NK-yQ_UfM+Ollie matson highlights", 
"bWBs7xo4Roo+OLLIE MATSON LEGENDS OF THE GAME (w JACK WHITAKER)", 
"Z_L5swhgEnU+Bruce Matthews", 
"PWxde_hTHmg+Bruce Matthews vs John Randle (1995) | OL vs DL Matchup", 
"I2ZxYO03Sfg+Top 10 Auston Matthews Plays from 2021-22 | NHL", 
"Eys9d8We1oE+Top 10 Auston Matthews Plays Of The 2021-22 NHL Season", 
"QIwxtsbf3Dk+Kevin Mawae highlights", 
"jFqY9XqjRxI+Center Kevin Mawae “Mr.Durability”", 
"71i6uwwih1w+Kevin Mawae Combine Workout | Seahawks Vault", 
"cwWulZ-jYtk+Kevin Mawae NFLPA Feature", 
"vtE-HSFMMC8+A Look Back At Don Maynard's Career | NFL Films | The New York Jets | NFL", 
"nJY7_SIH1oY+NFL Films: Don Maynard Long Touchdown vs Raiders During AFL Championship | The New York Jets | NFL", 
"3d6NVu1WNjo+Remembering Hall of Famer Don Maynard", 
"zksHfxZdMuI+Top 10 Pat McAfee Moments", 
"Td3R1vppAlk+Pat McAfee: The Perfect Combination of Funny and Dominant!", 
"K6rBLQ8GQA4+Christian McCaffrey Top Plays of the 2022 Season", 
"qssN-QOZvsI+Mike McCormack: Hall of Fame Football Offensive Tackle", 
"UtwpyCPx0E0+Mike McCormackinterview", 
"vKcPWxncN40+Michael McCormack breaks state career points record", 
"fkE1HO5WKYg+#89M Mike McCormack - Legends - 6-17-2022 Dallas County Speedway - In Car Camera", 
"SlzbUavEtg4+Randall McDaniel", 
"XhaeRSlHQNM+Randall McDaniel Induction Video", 
"z939HkMQQCk+Randall McDaniel destroys Mike Singletary", 
"3A3KkE5piTA+Randall McDaniel Play 60 Spot", 
"sMw1OCjlmVM+PHILADELPHIA EAGLES TOMMY MCDONALD [Full Highlights] 🦅", 
"XrMO1c5GLCc+Tommy McDonald: Forever An Eagle | Philadelphia Eagles", 
"O9BAl-X0w2Q+The STRANGEST Practice in NFL HISTORY | Tommy McDonald (1967 Falcons)", 
"HOK77JslrIk+Hugh McElhenny Highlights", 
"0zP_SBa8MpY+Hugh McElhenny Highlight Segment | NFL Highlights HD", 
"gbNF7tZYEXI+‘The King’ Reigned For 13 NFL Seasons – Hugh McElhenny: 1928-2022", 
"Oa31-pThXAw+1971 week 10 Hugh McElhenny", 
"dkqoM43kEDI+HUGH McELHENNY & THE 1ST PUNT RETURN FOR TOUCHDOWN IN MINNESOTA VIKINGS HISTORY (DEC. 17, 1961)", 
"b9JDLy63n-8+Remembering Hall of Famer Hugh McElhenny | 49ers", 
"wtf1dxqFEys+Class of 2022 Extended Knock - Art McNally", 
"2-u4JxbBYJo+Craziest \"Trick Plays\" in College Football History", 
"_gOX2zopwUI+Art McNally: Pro Football Hall of Fame Class of 2022", 
"-UwGH-slb3I+2019 J-Club Hall of Honor - John \"Blood\" McNally '24", 
"To-KPPzaxww+John \"Blood\" McNally 2019 SJU J-Club Hall of Honor Induction", 
"0nBS_gW-68Q+John “Blood” McNally – The Vagabond Halfback (Packers / Steelers)", 
"-bKtQbbgjzo+Sports' Forgotten Heroes - 23: Johnny Blood-NFL", 
"7KsiJ26Rj9I+Green Bay Packers vs. Boston Redskins1936", 
"cLkNnkWZzbc+The Football History Dude - John “Blood” McNally – The Vagabond Halfback (Packers / Steelers)", 
"utT4EEhSCWk+Miami LB Michael Pinckney Top Plays 2018", 
"5HwfCMGIe0M+Mike Alstott Highlights", 
"oLQ7ZX3n8mg+Mike Alstott's Ascent to Become the LAST Legendary Fullback! | Throwback Originals", 
"124mXNN89Ms+Wayne Millner: Hall of Fame Football End", 
"UYSZfz-5cbE+1935 Bill Shakespeare to Wayne Milner for Notre Dame Win", 
"-941wUFJ6jI+Horacio the handsnake - Wayne Millner", 
"oVxbkR4zsGw+TSN - Top 10 Wayne Gretzky Moments", 
"-thWuwjiIfM+Sam Mills career highlights | Pro Football Hall of Fame", 
"m1-5EjamoXI+Sam Mills Highlights: New Orleans Saints Ring of Honor Inductee 2021", 
"UK0Blv1_lFA+Sam Mills Career Highlights “Yes Indeed”", 
"MPDOCUDisR8+Bobby Mitchell Highlights", 
"eTH11CwLFa4+BOBBY MITCHELL WASHINGTON REDSKINS YEARS 1962-1968 (TRIBUTE & HIGHLIGHTS)", 
"Lx4UPNvUNls+jim brown BOBBY MITCHELL : SO GREAT HE MADE SUPERMAN (aka Jim Brown) Sweat!  part I", 
"JKlrdLBBg7Q+Ron Mix 2010 — Football", 
"bnLgoSNTB0c+Ron Mix | PFRPA Podcast #011 | Hall of Famer", 
"Tch4v0L0GHA+The Best Of Ron Swanson (Parks and Recreation)", 
"SSdDqNaASr0+Ron Baker Top Ten Plays", 
"YHNAz-5pg7M+Redskins Top Plays: Art Monk Breaks Record 10/12/1992", 
"LaXHKQH4Wec+JAMES ARTHUR \"ART\" MONK - NFL ALL-TIME GREATEST RECEIVERS - VOLUME 1 (PART 1)", 
"KM-xSbveZg4+Redskins Art Monk Career Highlights", 
"ZQECGqE9ags+Art Monk: Redskins Legacy | Throwback Thursday - HTTR4LIFE", 
"xcGnHJDrHe8+Joe \"Cool\" Montana Career Highlights | NFL Legends", 
"ao3S3q0R-CA+Warren Moon Highlights (Final Version)", 
"k0PPBjFvT3M+Rare Warren Moon Oilers highlights (Original TV broadcast footage)", 
"5eMXQ1AKHTk+Lenny Moore: The Most Explosive Running Back in NFL History", 
"eCMh_jj7E64+Lenny Moore", 
"lfRAcckQz2s+Randy Moss' Ultimate Career Highlight Reel | NFL Legends Highlights", 
"whagK_vAA48+Top 10 Moments: Bill Willis and Marion Motley re-integrate professional football", 
"JNRh_BAecJ8+Guard Mike Munchak “Mean,Massive,Mobile”", 
"x7c3AVGjG2E+Sports Vault: November, 1994.  Mike Munchak has his #63 retired by Houston Oilers.", 
"fMdTaBzlcj0+'You go fast enough to win every snap!' | Wired at #BroncosCamp with OL Coach Mike Munchak", 
"IynYVySJuPw+Mike Munchak Golf Classic", 
"q9dxb_NfVzk+Pittsburgh Steelers OL coach Mike Munchak teaches up OL at OTAs", 
"kfyzYF35meE+2022 Mike Munchak Charity Golf Classic", 
"x6qBLO2Z_7o+Anthony Munoz Ultimate NFL Career Highlights", 
"nCOBqvbunnw+When Anthony Muñoz Met Lyle Alzado (HD) 1983 NFL Season", 
"RmWtGLjFXOw+100 All-Time Team: Offensive Line | NFL 100", 
"oyKNZRN9saI+George Musso: Collinsville CUSD 10 Hall of Fame 2023 Inductee", 
"aFsi--5kJRs+George Musso Random HOF Chicago bears!", 
"P_NY-QSOfXs+College Football Best Plays of Week 2 | 2023-24 ᴴᴰ", 
"fbg0ud69N-o+KingGeorgeTV MOST VIEWED CLIPS OF ALL TIME!", 
"dw4cUVFMVEA+Top 10 Greatest Forgotten Plays in NFL History | NFL Films", 
"giVCWwv2uBM+Broadway Joe - Joe Namath Career Highlights", 
"Xcls3YDNRXE+NFL's Greatest Characters: No. 1 - Joe Namath | New York Jets | NFL", 
"AAVoBa4Io7A+Namath Fires Darts(Jets At Raiders 1972)", 
"HmpJWgaFk7A+1948 NFL Championship: Philadelphia Eagles 7, Chicago Cardinals 0", 
"bN9fBaQy1Qg+ESPN's Top Ten NFL Plays of the Past 25 Years", 
"1AhPX30nZgo+Earle Neale's Eagle Defense", 
"qT6LIHiCELw+How Ernie Nevers scored 40 points in a NFL Game", 
"SYjeAVqWryY+Two Minutes of Pro Football History: Nevers Again", 
"C7Ok01O_4Es+Ozzie Newsome Highlights￼", 
"W06VU6a8Qj0+The Wizard Of Ozz - Ozzie Newsome Career Highlights", 
"5EoRj8U7PKQ+Playing Like a Raven - Best of Ozzie Newsome | Baltimore Ravens", 
"Ia1RIzHD1V8+Pride for the Crimson Tide - Best of Ozzie Newsome | Baltimore Ravens", 
"Q7NFRLGJN44+Ray Nitschke  Career Highlights [Nfl All Time Greats part 1]", 
"Q2_qRvxNHkU+NFL - Special - Hardest Hits Hardest Hitters - Ray Nitschke & Dick Butkus & Lawrence Taylor", 
"UpEQbvqUWzU+ROMAN GABRIEL TRUCKS RAY NITSCHKE", 
"7k8CqYwtEu0+Chuck Noll's WORST Moment | The Day The Steelers Turned on Chuck Noll", 
"UVGUjZzdFrM+Top 20 Chuck Noll Quotes - The professional American football player, assistant coach & head coach", 
"FEx2sr2-zEA+NFL - Greatest Teams - Chuck Noll & The Pittsburgh Steelers   imasportsphile.com", 
"YYLMghJeIm4+Chuck Noll:  His Life's Work", 
"ctuzD5R80Mc+Leo Nomelini", 
"1xy2uO3JT9M+Nick Bosa Top Plays of the 2022 Season", 
"SBdta7TE4VQ+Bill Nunn: The Pittsburgh Steelers’ dynasty builder | Monday Night Countdown", 
"a08XEmy7lAg+Class of 2021 Hall of Fame 'Knocks' - Bill Nunn", 
"Pbfbbuu0q2Y+Do The Right Thing - Radio Raheem's First Appearance", 
"yw5LJhim114+Bill Nunn Tribute - Re Classics", 
"ZOHMZzBHbLU+BILL NUNN TRIBUTE", 
"kBzDeN_BlFo+Jonathan Ogden Ultimate NFL Career Highlights", 
"8ZRmTUET2sU+The best of Jonathan Ogden (peaceful playlist)", 
"E3VxFFy77x8+Merlin Olsen Highlights", 
"lw0YjPd14P0+Special - 1981 - Merlin Olsen Showcases The Year In Sports In 1981 In Highlights Of Greatest Plays", 
"so43Mp_2AzE+1976 St. Louis Football Cardinals: Conrad Dobler vs. Merlin Olsen", 
"VTNxHfZxYuQ+Jim Otto: Ironman", 
"H2VBv9SyCcQ+Best of Bedlam: Steve Owens 55 carries in 1969 (2011-11-29)", 
"G64Q6HMgqXk+CHARACTER HIGHLIGHT | STEVE FOX BEST PLAYS", 
"WIsRZH_j6fI+My 3 Most Favourite Steve Irwin Moments", 
"Og_AsF4W4RA+Steve Owen Goes Out with a Car Chase and a Bang | EastEnders", 
"rvnW5LVFJss+EastEnders - Phil Mitchell Vs. Steve Owen ( Feuds From 1999 - 2002)", 
"tSiyFVekDoE+Terrell Owens' Best Play of Every Season | NFL Highlights", 
"sw8dAcQ-aS8+Orlando Pace || Ohio State/St. Louis Highlights", 
"gkJXnoeb5dQ+Orlando Pace tops RJ Young’s list of top five Ohio State Football players", 
"uqoo9RfKsZg+Orlando Pace highlight Video", 
"kxG1p8km5b4+Orlando Pace vs Warren Sapp & Simeon Rice (2002) | OL vs DL Matchup", 
"is5gaq-yUK4+Alan Page Highlights - MVP", 
"i0hhBiHnrKk+Alan Page Highlights", 
"oQMuoICscl0+\"I'm Scared of Spiders, Snakes, and the IRS\" Best of Bill Parcells Mic'd Up", 
"dWloob4OI0Y+Bill Parcells really said this 💀", 
"D0ojO_HgUFo+How Bill Parcells would rein in Bill Belichick!", 
"cF4qWRM27uI+Clarence \"Ace\" Parker.  Duke Football, 1935-1936.", 
"4pw8Qn8JzxY+Ace Parker Dies at 101", 
"zCqCS8VvtH4+WAVY Sports Archive: 1987 Hall of Famer Ace Parker", 
"mfl-rQq5v_Q+Ace Parker's 100th Birthday highlighted on ESPN's PTI (Pardon the Interruption)", 
"n79HNXqt0Xo+Jim Parker Highlight", 
"-p2mZi685EU+Walter Payton Highlights (Final Version)", 
"uQz7LWdOYc8+Ultimate Walter Payton Highlights Tribute", 
"g4bMvYNSOJs+Every Drew Pearson Touchdown | Drew Pearson Highlights", 
"jc3a-hNy3BU+Drew Pearson: A Football Life", 
"Q05A0QJXzik+Greatest Sports Legends: Drew Pearson (1987)", 
"DkKboqeFnM8+The Best Of Joe Perry", 
"kr7xN2LlI1Y+Joe Perry Highlights", 
"nnl3HA8a848+Slash Gave Joe Perry Back His Prized Guitar | CONAN on TBS", 
"1Z944p7yC_8+Joe Perry and His Guitar", 
"Iz-x-ty6FA4+Aerosmith “Walk This Way” (Joe Perry Birthday) 9-9-2023", 
"iKdvV7POM6E+Pete Pihos Leads the Eagles' Charge in 1951 | Eagles 1951 Season Recap", 
"3ehUZhRFqw4+pete pihos", 
"pPsDpcWoN7Q+Chuck Bednarik, Pete Pihos Guide Eagles to Another Winning Campaign | Eagles 1953 Season Recap", 
"UMccbrww57U+PHILADELPHIA EAGLES PETE RETZLAFF Highlights", 
"vDrwuwvq1oc+Troy Polamalu Top 50 Most Dynamic Plays!", 
"dKYOCZFNuso+Top 5 Troy Polamalu Career Plays | NFL", 
"9rIt_5uZz4g+Will British Guys Be Impressed by Troy Polamalu? (FIRST TIME REACTION)", 
"LjVGUkEN0_U+Blitz '21: The Guardians of the Game — Bill Polian", 
"bN9fBaQy1Qg+ESPN's Top Ten NFL Plays of the Past 25 Years", 
"cpCXTSboSdE+Every Team's Best Play of Week 1 | 2023", 
"Q2P2jLIUDw4+BHM: FREDRICK \"FRITZ\" POLLARD", 
"68UdARAflF8+Tony Pollard Complete 2022-2023 Season Highlights", 
"WVoffFCielw+Films Encore Fritz Pollard   NFL Videos", 
"Oy6TwMsJmAw+\"Regulators, mount up!\" Best of John Randle Mic'd Up", 
"ApEVyirqQo4+Hugh “Shorty” Ray – NFL’s Mr. Einstein", 
"9JdcNABFz9A+The Football History Dude - Hugh “Shorty” Ray – NFL’s Mr. Einstein", 
"vAC2almlat4+Most \"Vicious\" Hits in Football History", 
"4kHc60heCzc+Andre Reed Breaks Down Top Plays of his Career | Buffalo Bills", 
"ngCWxmtpO2E+Andre Reed Hall Of Fame Buffalo Bills Highlights", 
"gcpBpA6U54U+The YAC - Andre Reed Career Highlights", 
"R5ipJeCS8b8+Andre Reed (YAC) career highlights part 1", 
"xxyFKD-M9-w+Ed Reed Top 50 Most Dynamic Plays!", 
"Rw45djupYxI+DAN REEVES DALLAS COWBOYS RUNNING BACK 1965-1972 (SOUTH CAROLINA)", 
"-49vGFUsR8o+The GAME That SAVED Dan Reeves' CAREER | Raiders @ Broncos (1987)", 
"RMggTGwrBDg+NBC Sports’ Peter King on the Lasting Impact Dan Reeves Left on the NFL | The Rich Eisen Show", 
"jpCMvlf69nc+Dan Reeves dies at the age of 77 | SportsCenter", 
"nzD8G0qdj5M+Mel Renfro Highlights", 
"J7LXXYXUw6A+A Dallas Cowboy for LIFE: Mel Renfro", 
"70-Cxfa19KM+MEL RENFRO AND CORNELL GREEN: THE GREATEST SCB TANDEM IN DALLAS COWBOYS HISTORY!", 
"k0qTAdIsKts+Darrelle Revis' Top 10 Plays of Career | NFL Highlights", 
"BFqdoj4a5jQ+Darrelle Revis 2009-2010 Highlights- Pure Lockdown", 
"LkyJfOvl9uY+Jerry Rice Top 50 Greatest Plays!", 
"On_nvX2DTTw+How Good Was Jerry Rice Actually?", 
"cWjJUhaE18U+Les Richter's HOF Highlights", 
"jD9bcDAGkvQ+Les Richter Profile - 1992 NASCAR Video Magazine", 
"KhOKEEMgZio+Les Richter", 
"q6qe_7sK-6Q+John Riggins Highlights", 
"GLSn9hR5j0s+WHY THEY CALL JOHN RIGGINS \"THE DIESEL\"", 
"QkOuJXhvdJw+John Riggins Best Highlights", 
"tQ-GrsNJezA+Ken Riley Highlights", 
"UYxzqD0T_O8+An Everlasting Flame l Ken Riley", 
"l6IIfhHFb7M+PHILADELPHIA EAGLES JIM RINGO Highlights 🦅", 
"sgKAPWVXVMg+Kramer’s Titletown Teammates - Pt. 7 (Jim Ringo)", 
"9cqsIedJew4+Jim Brown's Top 5 Runs", 
"pbRoQ1cZDXo+Jim Brown Highlights (Final Version)", 
"GXV-ISVySwQ+Willie Roaf vs Charles Haley (1994) | OL vs DL Matchup", 
"kiWZjLHs0sc+NFL Hall of Famer Willie Roaf", 
"FlU48FI25SY+\"Time Out\" with Irv Smith Segment with guest Willie Roaf", 
"jM4oY9OPt04+David Robinson Top 10 Plays of Career", 
"rejE5G-mESo+David Robinson Top 10 Career Dunks", 
"Mpo20dOAkeY+Johnny Robinson Highlights", 
"YoJ22JLnryI+69 Chiefs Johnny Robinson HD", 
"cugF6RcCRWw+BEST OF Johnny Robinson! | The X Factor UK", 
"jKHUzZbwRhM+Johnny Robinson | Louisiana Legends", 
"6yy7kfv8GVY+Andy Robustelli: Hall of Fame Football Defensive End", 
"vjRMXQgoxWk+Robustelli mementos arrive in Canton", 
"pdWHdPqPCp8+A Football Family", 
"xYmdmemfbds+TOP 5 New York Giants of All-Time", 
"Ed4YmyArNRE+Coughlin talks about former Giant defensive end star Andy Robustelli", 
"0Ycg4qTT_kU+Steve Sabol profile about Art Rooney and The Chief Stage Play", 
"QjXsIYcwIsQ+Wayne Rooney [Best Skills & Goals]", 
"1RsEUy7uyxk+A tribute to Dan Rooney | Pittsburgh Steelers", 
"8mykfNv-LcU+Dan Rooney Speech at Patriot All-America 2020 at the Wigwam", 
"MCNNPNT157Y+Sports century pete rozelle", 
"tgohunc6djM+Deals of the Century - Pete Rozelle", 
"JJl02sQlOJQ+Pete Rose Top 14 Moments", 
"f0BCvV0oX9o+[HD] Pistol Pete Maravich  - TOP 20 PLAYS Ⓒ 2016", 
"ZVaSEsc2UZ8+A Football Life - Ed Sabol HD", 
"eJyYnm-YQpo+Steve Sabol NFL'S greatest moments, Nice guys finish first", 
"eJyYnm-YQpo+Steve Sabol NFL'S greatest moments, Nice guys finish first", 
"uX1USppL4AI+NFL Quarterback Bernie Kosar: Master of the Unorthodox w/ Steve Sabol", 
"Nh0wTYWOHoU+Ed Sabol's last film", 
"eXp6q4wDgJE+Remembering Steve Sabol A.K.A. President Of NFL Films (1942-2012)", 
"CrlO5mMqn7Y+Charlie Sanders ULTIMATE highlights", 
"VThNEGnVQTo+Deion Sanders Top 50 Most Game Breaking Plays!", 
"uHBC41GxBBI+Warren Sapp - # 99 (Career Highlights) (Vol. 1) (pt. 1/2)", 
"2Fb6kiQ2Y9A+Gale Sayers Highlights (Final Version)", 
"-iBhsGRo92I+Best football run ever/ Gayle Sayers", 
"arlzLZERgX0+Joe Schmidt: A Lions Legend", 
"peESZ0AK14g+Rugby Player Reacts to JOE SCHMIDT #84 The Top 100 NFL's Greatest Players!", 
"poDinJYvxqw+Top 100 Extra - Jerry Glanville on Joe Schmidt", 
"kTQroIBc-F4+From The Vault: Tex Schramm HOF Jacket | Dallas Cowboys 2020", 
"oaz_UfJrRpo+Tex Schramm, Dallas Cowboys Team President, Dies (2003)", 
"-MiFFxdS3SY+Cowboys' Top 10 Plays | 2021 NFL Season", 
"A65lL66RysY+Cowboys Top Plays vs. Saints", 
"E2xPRT75lk4+Junior Seau - San Diego Chargers Highlights!!!!!", 
"0qkX6j3R7xc+Junior Seau Highlights (1969-2012) Tribute to a Legend", 
"KhWf8q3UHIk+Junior Seau 2015 Pro Football Hall of Fame profile", 
"iiRLUad8G84+Lee Roy Selmon Career Highlights", 
"AQ9Sg6neUUY+Lee Roy Selmon Highlights", 
"iu5VM8pKDNY+Lee Roy SelmonTribute", 
"bs5RjsqBB80+Richard Seymour Highlights", 
"8IAtvtVRK1M+Richard Seymour’s Road to Canton | Patriots & Pro Football Hall of Fame Career Highlights", 
"bw5X4oDmSg8+Bill Belichick Recounts Coaching Richard Seymour (+ Highlights) Prior to His Patriots’ HoF Induction", 
"hvh0aFRvp5M+Richard Sherman's Best Career Plays with the Seahawks | NFL Highlights", 
"X5MDPJbcjhI+Shannon Sharpe's Career Highlights | Broncos Throwback", 
"XFvupl4bmmg+Shannon Sharpe & Chad Johnson react to Minnesota Vikings at Philadelphia Eagles | Nightcap", 
"IADX7mh98RU+Shannon Sharpe Hit on Chris Slade (1998)", 
"ny3edEpsymc+Bill Shaw", 
"T4RRUhZmHhg+BILLY SHAW HALL OF FAME 1999", 
"khMzsOtIrD8+Bills Hall of Fame Series: Billy Shaw", 
"91Pi1UU0S9Q+Billy Shaw Hall of Fame Football Offensive Guard", 
"nxse0-tKrJ4+Hometown Hall of Famer Billy Shaw", 
"OYtBrGZCbm0+The Billy Shaw HOF TTM Autograph \"Player Era Project\"", 
"BYfOis2caeQ+Art Shell Expected To Be Drafted Higher During 1968 Draft | My Draft Story | Las Vegas Raiders", 
"n-Tgh884kWw+Art Shell emotionally explains what it means to make All-Time Team", 
"96nQdmi_GXo+Donnie Shell NFL Highlights", 
"dI0XOLJBhno+DONNIE SHELL NFL ALL-TIME LEADER INT BY STRONG SAFETY (51)", 
"TFUOMCyBNUg+Hall of Fame - Donnie Shell - Highlights", 
"2yAnTm3338E+Donnie Shell's Famous Hit on Earl Campbell", 
"DHS1rd9izzI+Pittsburgh Steelers Hall Of Famer Donnie Shell On Playing With Other Steelers Legends", 
"jwBybxZ5FNY+Will Shields’ Open Field Dominance", 
"_Mp3zlZxwgs+Will Shields teaches offensive linemen who want to play in pros", 
"g5NtWln_F8U+NFL Play 60 workout with Will Shields", 
"jBHXeGO2ZmI+Athletes Hone Skills At Will Shields' Fitness Center", 
"8ctngAhF0I8+Sportscentury: Don Shula", 
"MoFbhL1cKq4+Legendary Coach Don Shula & Nick Buoniconti | The Many Lives of Nick Buoniconti | HBO", 
"Gr0glOxW5LM+Mike Ditka calls Don Shula one of the best coaches of all time | SportsCenter", 
"o6hx_rXZark+OJ Simpson Highlights - The Juice", 
"xTTHmYKFdrQ+O.J Simpson (The Best Player of The 1970's) NFL Legends", 
"ygDPt7ssOJ8+Mike Singletary Ultimate NFL Career Highlights", 
"jDQsYoxXPMQ+Mike \"Samurai\" Singletary Career Highlights", 
"KG0Doco0FxA+Duke Slater: Groundbreaker and Champion", 
"3phSxEYavSw+Duke Slater selected to Pro Football Hall of Fame Centennial Class", 
"ZgkSaSVos_c+Duke Slater - Addison Stremel (Sports Rhetoric Final)", 
"WunLz6A9BOg+Best of the Decade: Top Plays #DukeDecade", 
"h3I_LNqxuXs+Duke Basketball: Top 10 Plays of 2022", 
"XWHMgYYbwiY+JJ Redick highlights: NCAA tournament top plays", 
"Q7HtBpHDtzk+Jackie Slater", 
"mBXP5NC3arg+Jackie Slater vs Reggie White (1990) | OL vs DL Matchup", 
"rjvq0LyG7o4+Matthew Slater 8x NFL Pro Bowl - 2019 NFL Season Highlights - New England Patriots", 
"QnPFzXMZVxM+Bruce Smith Highlights", 
"iqVDyVmPQjI+Bruce Smith Buffalo Bills Sacks", 
"e8iYK2crylM+Thunder and Destruction - Bruce Smith", 
"7sXiTGfcDno+Emmitt Smith's \"Mr. Consistent\" Career Highlights | NFL Legends", 
"waJJCoCcMzs+JACKIE SMITH ST. LOUIS CARDINALS TE 1963-1977 ULTIMATE HIGHLIGHTS (PRO FOOTBALL HOF CLASS OF 1994)", 
"VbO2wlxYeWw+Jackie Smith drops sure touchdown", 
"hdw30E6E2Pk+Retro: Jackie Smith Highlights", 
"e-fvrLoUJpY+Mac Speedie Selected to Pro Football Hall of Fame Centennial Class", 
"0itbqR5Ro0s+Mac Speedie: Football End", 
"4HdB8qrxYLc+Mac Speedie's Daugther Wholesome Speach | 2021 Hall of Fame", 
"7ZsLx_mCB3Q+Ed Sprinkle", 
"mtnEJfEdOlU+Ed Sprinkle selected to Pro Football Hall of Fame Centennial Class", 
"3J7OX1L40uU+Ed Reed's Ridiculous Career Highlights: The Ultimate Ball Hawk | NFL Legends", 
"JjlEGz112DU+Ed Sprinkle ● A Simple Tribute", 
"J-EQ4ttlgFM+Remembering Bob St. Clair A.K.A. Pro Football Player (1931-2015)", 
"fFVQLMUFOpU+Bob St Clair Hall of Fame Football Offensive Tackle", 
"X0zF0i8RYIU+San Francisco 49ers Hall of Famer Bob St. Clair", 
"Fs_Zi-orxkQ+San Francisco 49er Legend Bob St. Clair", 
"iVHJ79hKxX8+2010 WCC Hall of Honor Inductee: Bob St. Clair, USF", 
"B91P9jli_fc+Bob St. Clair ● A Simple Tribute", 
"jkI4511UrGE+KEN \"SNAKE \" STABLER 1974 NFL MVP SEASON HIGHLIGHTS", 
"3qIWNboXD5o+Top John Stallworth Touchdowns | John Stallworth Highlights", 
"rVDxeiy9Jno+John Stallworth Highlights", 
"vIneNC7W8SM+Lynn Swann & John Stallworth", 
"nluXKFKxBuo+Butkus   Monster of the Midway", 
"lsWqX2LgXN4+DICK BUTKUS: HARDEST HITS (Old School Football)", 
"tWgV2Qw7ViA+Dick Butkus- NFL's best ever : professionals", 
"sSI3quJVwgI+Bart Starr Highlights", 
"_zEUk_R1AlY+Bart Starr Remembered - Enhanced 1080p/60fps", 
"PtjsYkqt1Lw+Roger Staubach Highlights", 
"5q2CVZA7_zQ+Roger Staubach Highlight Video", 
"h5Qo2jHJzow+Ernie Stautner: NFL Defensive Tackle & NFL Defensive Coordinator", 
"T81Jt6cG11Q+Where the Steelers Tough reputation started 💪🏻💪🏻💪🏻🏈🏈🏈", 
"_NBkYqOYUWg+Stautner Moments", 
"xcB9f-BUuOE+NFL All-Time Team: Jan Stenerud", 
"i5jXd9i30ok+Jan Stenerud - Kicker i Kansas", 
"HZBUmm3KvZM+Patrick Mahomes' Top 26 Plays", 
"MUdT2FmorlA+Hall Of Fame Kicker Jan Stenerud Announces His Retirement From The NFL (12-19-1985)", 
"6BTakXDJNCQ+oline Dwight Stephenson", 
"opBWHUvQ6mo+NFL All-Time Team: Dwight Stephenson", 
"yEKLxxDFjKQ+Dolphins alumni throwback: Dwight Stephenson | Dolphins Daily", 
"CaSpYwopf8w+Gridiron Glory: Dwight Stephenson", 
"efM_JbJiwnQ+MLB Hottest Moments", 
"2srCohpdd6Y+\"I'll put your *** on the ground next time, bubba!\" Best of Michael Strahan Mic'd Up!", 
"B2kwH4yVeNY+Top 10 Giants: Michael Strahan | NFL", 
"Jd0EMw7YMWI+NFL - 1970 - NFL Film - Super Bowl IV Memories - Chiefs VS Vikings - Coach Stram's Miked On Sideline", 
"OPAcT2KBupI+Super Bowl IV Mic'd Up: NFL Coaches React to Hank Stram & His Chiefs | NFL Films Presents", 
"YVEQnRy5Ttw+Hank Stram - Steve Sabol", 
"AWaMuwebn9A+SFV CE Ken: Strong Frame Trap Sequence (With Commentary)", 
"0xzI6BFH-fI+Redskins Top Plays: Ken Houston's Big Stop 10/8/1973", 
"Vfb6yXE-ICg+Ken Strong Central Michigan University", 
"Dt6d7jqJ9jk+Ken Strong Stadium Recording", 
"LCkMCANJdFE+Joe Stydahar: Hall of Fame Football Tackle", 
"Wy3twFMqZVg+Joe Mixon's Top 10 Plays", 
"e0Bt1KG4Y7k+Joe Montana Top 50 Most Magical Plays!", 
"TxChuwTXmFU+Top 10 Joe Burrow plays | 2022 season", 
"8pckTX9r3Qw+Lynn Swann Highlights", 
"vIneNC7W8SM+Lynn Swann & John Stallworth", 
"wfqk3n9xZ44+Steelers Great Lynn Swann Compares NFL Eras, Bashes Bradshaw's Inaccuracy | The Dan Patrick Show", 
"ndAib7YVe9U+Paul Tagliabue Full Hall of Fame Speech | 2021 Pro Football Hall of Fame | NFL", 
"ALBQVPLNWE4+Power of Sports | Game Changers - Paul Tagliabue", 
"3PPxzvshjNo+Paul Tagliabue selected to Pro Football Hall of Fame Centennial Class", 
"CVanbSDPI9U+Paul Tagliabue on The Edge of Sports", 
"YKz1inK9Uj8+Paul Tagliabue 2020 Pro Football Hall of Fame Induction Speech | NFL on ESPN", 
"LasLWRfavOQ+Fran Tarkenton Eludes Several 49ers Defenders, Completes Long Pass For TD | NFL 100 Greatest Plays", 
"jJOeacMVFuk+FRAN TARKENTON 1961 ROOKIE SEASON HIGHLIGHTS (MINNESOTA VIKINGS) (GEORGIA)", 
"wETndZ3InH4+CHARLEY TAYLOR 10 LONGEST NFL TOUCHDOWNS", 
"TsJzULsJ8IU+Redskins Top Plays: Charley Taylor Goes Deep 12/31/1972", 
"jvyLJkb1LXA+NFL GREATEST TOUCHDOWN CELEBRATIONS VOL. 1 - CHARLEY TAYLOR (WASHINGTON REDSKINS)", 
"2xw06FDJbt0+CHARLEY TAYLOR MAKES PHENOMENAL CATCH, TAKES HARD HIT(S)", 
"eF5OZVuTYNY+Jason Taylor Miami Dolphins Career Highlights", 
"vGItow0_0WM+Jason Taylor career highlights", 
"oSHLqoeRccM+NFL Tough Guys   Jim Taylor", 
"iv0CztZTtFg+Jim Taylor Highlights", 
"oWB9ia_ZPjk+Lawrence Taylor - The Greatest Of All Time", 
"_ggXb-JeGVE+Lawrence Taylor Highlights", 
"N5zdM1E8m0k+Lawrence Taylor Giants Career(top plays)", 
"VuS8BZZpe2g+Chief Sack Master (DT58) - Derrick Thomas Career Highlights", 
"6ZNr8xYC-Z8+Derrick Thomas Highlights", 
"7WIijeg0V1A+1990: Derrick Thomas NFL Record 7 Sacks", 
"ki8zisEzadw+Emmitt Thomas WR/KR Highlights", 
"pSgp7h0eTIU+Emmitt Thomas 2013 highlights", 
"gA8iex4M9o8+BLACK COLLEGE FOOTBALL HALL OF FAME CLASS OF 2016 ENSHRINEMENT VIDEO: EMMITT THOMAS", 
"MACBRMbnc5I+🏈 Emmitt Thomas Is One of The Greatest Players in Kansas City Chiefs History", 
"VcHvmGUtHyo+Emmitt Thomas: Hall of Fame Football Cornerback", 
"KeE1om9s7ug+10,363 - Joe Thomas Career Highlights", 
"o9-a1pJKmLE+Joe Thomas' Incredible Journey to the Hall of Fame", 
"NNWMsSymLAQ+Aaron Donald vs ‘ALL PRO’ Joe Thomas (OL vs DL) Unstoppable Force vs Immovable Object!", 
"DowThizm_gQ+Thurman Thomas - The Thurmanator pt. 1 (Career Highlights)", 
"QxT4ptxDCsM+Zach Thomas \"Baby Elephant\" Career Highlights | NFL Legends", 
"806fo8lN-FI+The Zach Attack - Zach Thomas Career Highlights", 
"taDD5rIc8k8+Hall of Famer Zach Thomas breaks down his most iconic plays | Miami Dolphins", 
"bsFX9WfQo4U+The only running clip of jim thorpe", 
"0zVXHxoNl3M+Jim Thorpe: All American Athlete, Olympian, Hero", 
"Ws06utPPl70+Jim Thorpe - Greatest All-Around Athlete", 
"cwX5DPsLY8k+BRIGHT PATH STRONG presents: Jim Thorpe -- The World's Greatest Athlete", 
"D13nuxf3PHQ+Jim Thorpe, the greatest athlete of all time?", 
"A5lpCol3xeI+Vikings Mourn Passing of The Legendary Mick Tingelhoff", 
"xgJeF4-wUyY+Mick Tingelhoff 2015 Pro Football Hall of Fame profile", 
"WPdOtWf8u1c+Durable, Reliable, 'Quick Mick' Tingelhoff: 1940-2021", 
"pK-Wp97ZYRQ+Andre Tippett Highlights", 
"1W9vnMhcx4c+NFL's Merchants of Menace - Andre Tippett", 
"WHCbpx3Yb8E+Andre Tippett Highlights", 
"mpdGL4VZw2c+Patriots Red Jersey Throwback Hype Video Narrated by Andre Tippett | 2022 NFL Week 5", 
"gdUmHWyY47A+Y.A. Tittle Highlights (Final Version)", 
"fRh9LMff5TA+Flashback Friday: Y.A. Tittle throws 7 touchdowns", 
"QxrEESaTsCU+I Recreated the TOP PLAYS From NFL Week 1 in Madden!", 
"OTIeSpYPmRs+LaDainian Tomlinson Top 50 Most Electrifying Plays!", 
"dzqUvuS7e9c+LaDainian Tomlinson career highlights", 
"s4WSW8nXB4Y+LaDanian Tomlinson ULTIMATE Chargers Highlights (2001-2009)", 
"My2r0lEA_sw+George Trafton: Hall of Fame Football Center", 
"dLFubVoYVkQ+Topanga Beach houses and surfing, 1973", 
"FP-RGz22NlU+The Chicago Bears Hall of Fame", 
"KCFTF2tFa40+Blue Juice - Po' Lil Rich Boys", 
"vlxFdLVQ30A+Charley Trippi, Georgia (1942, 1945-1946)", 
"jErk9oltwGc+Remembering Hall of Famer Charley Trippi, ‘Dream Backfield’s’ versatile leader: 1921-2022", 
"-4CxAQfxYPo+Pardon the Interruption: Happy 100th Birthday, Charley Trippi!", 
"IQ3m-STU8W0+Chapter 10 - The Story of Charley Trippi", 
"AWAsI8xF5BQ+UGA football legend Charley Trippi turns 100", 
"nuIdRIJY5Kw+Offense on Defense: Giants Legend Emlen Tunnell - A Hero On & Off the Field | NFL Films Presents", 
"Dk3j8olxtN8+Offense On Defense (The Gremlin) - Emlen Tunnell Career Highlights", 
"_UgoBXTBiGo+NFL All-Time Team: Emlen Tunnell", 
"Z0UwUdhLPVU+Clyde \"Bulldog\" Turner - HSU Cowboy Football Legend", 
"da4pwsgd2cg+Bulldog Turner: Hall of Fame Football Center and Linebacker", 
"25E8ehjcwxI+Chest Fever - 07 - Story of Bulldog Turner (NFL Hall of Fame C) - www.chestfever.com", 
"dUYuZT8KULo+Brian Urlacher Clyde Bulldog Turner dual g/u, Knute Rockne worn jacket, Richard Dent g/u an more!", 
"EEznr9nz_Wo+Pro Football Championship game 1940", 
"R8OGOYyzsZo+Johnny Unitas Highlights - The Greatest", 
"t-X0TOOYw9w+Johnny Unitas Highlights (Final Version)", 
"7GPZCXURhgA+The CRAZIEST TOUCHDOWN of Johnny Unitas' CAREER | Colts @ Patriots (1970)", 
"t5ciMeEluIg+NFL Guards Gene Upshaw (Raiders) & John Niland (Cowboys) wired (1973)", 
"YACOUsgMEro+Brian Urlacher 😳 ABSOLUTE SAVAGE I Best Highlights", 
"JVFLGBhgyHk+When Brian Urlacher MET Gronk! ‘ROOKIE’ VS VET! (TE Vs LB) Rob Gronkowski Vs Brian Urlacher", 
"q1pz46gJUTo+Brian Urlacher's Son HITS HARD like him 😤 | 2024 Notre Dame commit Kennedy Urlacher | HIGHLIGHTS 🎥", 
"vqWVA27Pe-Y+1969 week 5 Norm Van Brocklin", 
"5OOBiZPKv5E+PHILADELPHIA EAGLES NORM VAN BROCKLIN Highlights 🦅🏆", 
"Nxm_HJl1DKQ+Steve Van Buren Highlights", 
"z_M8lP8AdcI+PHILADELPHIA EAGLES STEVE VAN BUREN Highlights 🦅⚡🏅🏆", 
"E5B1k1Or2_o+Top 10 Philadelphia Eagles of All Time | NFL Films", 
"p4646Omi4JQ+Remembering Steve Van Buren", 
"qzueQv8K_N0+PHILADELPHIA EAGLES DICK VERMEIL Highlights 🦅🏆", 
"OTUkSXcyP44+Dick Vermeil - 2000", 
"UZrmz5DYWTM+Dick Vermeil highlight video", 
"YuugwnUz2nY+The Doak Walker Award Winner | Bijan Robinson Texas Highlights ᴴᴰ", 
"W0Rx0Yic3cQ+Doak Walker Highlights", 
"x05E3lCggpI+Doak Walker highlights", 
"X6mFQvZxX88+Bill Walsh: A Football Life - The West Coast Offense", 
"fd_CnRkKOqA+A Football Life Bill Walsh", 
"_E8Oy-Dx4vU+The CRAZIEST COMMENT of Bill Walsh's CAREER", 
"PwLHOCaqmMg+The Impressive Bill Walsh Coaching Tree", 
"87OMd3Lwwvg+Top moments from DeMarcus Ware's Broncos career | NFL Throwback", 
"mfbqnTGccPc+The best plays from Pro Football Hall of Famer DeMarcus Ware's Broncos career | Historic Highlights", 
"jLL2AoL2beQ+Paul Warfield: The Most Underrated WR in NFL HISTORY???", 
"1nM_kd8T-98+Dolphins Daily | A look back at Paul Warfield's career", 
"iNygzb8bsWE+Kurt Warner Highlights", 
"MH0iffeqeI4+The Greatest Show on Turf is Born! (Ravens vs.  Rams 1999, Week 1)", 
"KusMzrAikhM+Bob Waterfield Highlights", 
"fXHnRRgwxFM+Bob Waterfield", 
"m-ARK0hXKBE+Bob Waterfield", 
"XxdlIwh0XfU+Pro Football Championship game 1945", 
"uVRGQqCXQpg+Mike Webster Ultimate NFL Career Highlights", 
"8ijs8v6SKek+Center Mike Webster “Iron Mike” Highlights", 
"nzc0Lrxw3KY+mike webster geene atkins interview", 
"k-DZYP90qh4+Concussion (2015) Justin Strzelczyk Visits Mike Webster", 
"1WTfaVluZ40+Roger Wehrli Highlight Video", 
"PE85W2PABWM+The GREATEST Play of Roger Wehrli's NFL CAREER | Giants @ Cardinals (1982)", 
"4USZx7a_PM8+1982 Week 16: Roger Wehrli TD on Fake FG", 
"2jFbQ1H6tg0+Roger Wehrli 1968", 
"VFd3c-8QO3c+Roger Wehrli Acceptance Speech", 
"k9fvssRdRxg+Roger Wehrli: Hall of Fame Football Cornerback", 
"N7EiuOlYe9s+Arnie Weinmeister: Hall of Fame Football Defensive Tackle", 
"xWSjivdueI4+Highlights: New Rams LB Bobby Wagner's Top Career Plays", 
"MjgO6il5mwo+GameDay's Great Eight Top Plays - Week 1", 
"bN9fBaQy1Qg+ESPN's Top Ten NFL Plays of the Past 25 Years", 
"FDrGwi7Se_s+Randy White Ultimate NFL Career Highlights", 
"J3nVTgfOW-g+Randy White career highlights", 
"HejaNQZZnNU+How GOOD was Randy 'The Manster' White really?", 
"1uGWTzhoJMk+First & Then: Ed \"Too Tall\" Jones & Randy White | Dallas Cowboys 2021", 
"ahdEe_sUYPY+Reggie White (DE, Eagles, Packers) Career Highlights | NFL", 
"ROeUncqW_lg+Dave Wilcox - San Francisco 49ers", 
"RVzdQ81XeRI+Dave Wilcox \"The Intimidator\"", 
"ahn3twmYkQM+Singer-Songwriter David Wilcox Plays His 1996 Olson SJ", 
"2X5Fj6BJC_M+Remembering 'The Intimidator,' Dave Wilcox: 1942-2023", 
"J4DzPgmIBjA+David Wilcox LIVE at Casino Rama Resort", 
"k9LN-pJ42TU+Aeneas Williams Highlights", 
"k_14M-15mVw+Every Aeneas Williams Touchdown", 
"USVOKmtM_oY+Aeneas Williams   Highlights", 
"whagK_vAA48+Top 10 Moments: Bill Willis and Marion Motley re-integrate professional football", 
"qFxJXHy_jaE+The Forgotten Four: Bill Willis", 
"HvpThSdt5Lg+Biggest Moments of Willis McGahee's Career | Buffalo Bills", 
"AojdObDtapY+Ohio State Football Bill Willis Feature", 
"qF1Kz-058Ts+Larry Wilson: 1972 NFL Films Highlights", 
"IoEeZjAXizs+Larry Wilson HOF Highlights", 
"skLIaPEdM64+Larry Wilson Highlight Video", 
"-5UIlmC3IU8+Ralph Wilson Jr. induction vignette - Chris Berman", 
"jBwFqNRHbrs+Ralph Wilson Jr. Hall of Fame Speech", 
"m5Nk84B5muI+Founder of Bills, Ralph Wilson Jr. dead at 95", 
"_UWdz1bv7Uk+The time Ralph Wilson demanded the Bills draft running back Dwayne Wright", 
"Aqc8vXVZPRo+Midwest Invitational Rodeo, Ralph C. Wilson Jr. Centennial Park, Kris Johnson | ABJ Full Episode", 
"z7yWmHWZ1B8+Bills fans honor Ralph Wilson Jr", 
"hKPXD0AaCj8+Kellen Winslow Sr. Ultimate NFL Career Highlights", 
"RckJd63brDM+Kellen Winslow Jr  Buccaneers Highlights", 
"OTArs5Rl-M0+PHILADELPHIA EAGLES ALEX WOJCIECHOWICZ Highlights 🦅🏆", 
"63-Lu75W2Ko+Alex Wojciechowicz: Hall of Fame Football Center and Linebacker", 
"ZiuxW2O3fMs+Alex Wojciechowicz", 
"TuaXEgHoux8+Top 100 Alex Ovechkin Goals EVER!", 
"wHelP_5WHGM+Ron Wolf's 2015 Pro Football Hall of Fame speech", 
"yFa1eikURXA+Ron Wolf on learning the history of the Green Bay Packers", 
"oIXmS76e_zg+Ron Wolf: The Legacy & Influence of a Hall of Fame GM", 
"n5ctPAqt_wk+MLB Greatest Outfield Throws of All time", 
"ldQKfRDCUnc+How Ray Nitschke Helped Ron Wolf", 
"1cXEBh13qjA+NFL legend Willie Wood remembered for his DC roots", 
"zbi4WkcUYiI+Funny commentator", 
"iKc0rDlIO78+Willie Wood helped countless black athletes by the stuggles he faced", 
"Uh8XOgH00iI+Willie Wood Tribute - Gone But Never Forgotten", 
"2FYZGtJMMZI+Kramer’s Titletown Teammates - Pt. 11 (Willie Wood)", 
"pfnqzhtfzn4+1981 preseason (Willie Wood)", 
"k7fi3G3UPBU+Charles Woodson Top 10 Plays | Green Bay Packers", 
"UgWgrMCC35I+Charles Woodson |The College Legend| Highlights", 
"D9ZPvWH-ysA+Faithful, Fearless - Rod Woodson Career Highlights", 
"ptD8PMequE4+Rod Woodson || 1993 \"DPOY\" Highlights", 
"NaB1gKFIGOw+Every Rod Woodson Defensive TD | Rod Woodson Highlights", 
"zXGJMgz8S80+Rayfield Wright, Dallas Cowboy Offensive Tackle 1967-1979", 
"050oenWfeTM+Rayfield Wright: 1945 - 2022", 
"HRwKfjtZfc4+Rayfield Wright  Hall of Fame Football Offensive Tackle", 
"cV02inyfT78+Rayfield Wright - Hall of Fame speech (2006)", 
"qZe4sXhJVyc+Rayfield Wright Hall of Fame Enshrinee Profile 2006 HD", 
"dQg4OP71rJw+Ron Yary Hall of Fame Football Offensive Tackle", 
"uuwS13LSmwM+USC great Ron Yary dreamed about dominating UCLA in Crosstown Showdown", 
"15zJTqEIoA0+Ron yary TourIsrael4U with The Stars.", 
"3_-CcR7TZfg+Signing Day Stories: USC's Ron Yary", 
"5TBgUxgp-jY+The Ron Yary HOF TTM Autograph \"Player Era\" Project", 
"7_pPHMppnas+Ron Yary", 
"QkKfT7otxMc+Bryant Young Highlights", 
"kMO9_PPgDaw+Bryant Young is Headed to Canton | 49ers", 
"nv8ewEOpSsg+Bryant Young", 
"kSPRXL2FlRg+George Young - St.Kilda Career Highlights 1973 - 1978", 
"JDYSFh3GEjk+When Paul George BECAME A LEGIT SUPERSTAR! BEST Highlights & Plays from 2013-14 NBA Season!", 
"LbPwwmEcws0+Steve Young's famous 49-yard game-winning touchdown vs. Vikings | October 30, 1988", 
"xut6kA2Vnmc+JACK YOUNGBLOOD All-Time best!  Hall of Fame Defensive End!  SACKS, TACKLES, CLUTCH PLAYS!", 
"IyvXaCkS61U+JACK YOUNGBLOOD HIGHLIGHTS", 
"4gTgU_MNgt4+Jack Youngblood (The John Wayne of Football) NFL Legends", 
"TqkTYHhKcL0+Gary Zimmerman was 'one of the best to ever play the game' | Broncos 100", 
"PET8DPGtuqA+Broncos 100: Tom Nalen, Gary Zimmerman, Matt Paradis, Ryan Clady", 
"YJCVrvO-N-U+Gary Zimmerman HOF Career Recap", 
"Hk-h9NozoN0+Gary Zimmerman: Hall of Fame Football Tackle", 
"ur87Aui5qX0+Gary Zimmerman"];