import requests
import html
from bs4 import BeautifulSoup
import json

BASE_URL = "https://www.profootballhof.com/players/"

# List of player names you provided
player_names = [
"elroy crazylegs hirsch",
"Herb Adderley",
"Troy Aikman",
"George Allen",
"Larry Allen",
"Marcus Allen",
"Lance Alworth",
"Morten Andersen",
"Doug Atkins",
"Steve Atwater",
"morris red badgro",
"Champ Bailey",
"Ronde Barber",
"Lem Barney",
"Cliff Battles",
"Sammy Baugh",
"Bobby Beathard",
"Chuck Bednarik",
"Bert Bell",
"Bobby Bell",
"Raymond Berry",
"Elvin Bethea",
"Jerome Bettis",
"Charles W Bidwill Sr",
"Fred Biletnikoff",
"George Blanda",
"Mel Blount",
"Tony Boselli",
"Pat Bowlen",
"Terry Bradshaw",
"Cliff Branch",
"Gil Brandt",
"Robert Brazile",
"Derrick Brooks",
"bob boomer brown",
"Jim Brown",
"Paul Brown",
"Roosevelt Brown",
"Tim Brown",
"Willie Brown",
"Isaac Bruce",
"junious buck buchanan",
"Nick Buoniconti",
"Dick Butkus",
"Jack Butler",
"LeRoy Butler",
"Earl Campbell",
"Tony Canadeo",
"Harold Carmichael",
"Joe Carr",
"Harry Carson",
"Cris Carter",
"Dave Casper",
"Guy Chamberlin",
"Jack Christiansen",
"earl dutch clark",
"George Connor",
"Jimmy Conzelman",
"Don Coryell",
"Jimbo Covert",
"Bill Cowher",
"Lou Creekmur",
"Larry Csonka",
"Curley Culp",
"Al Davis",
"Terrell Davis",
"Willie Davis",
"Brian Dawkins",
"Dermontti Dawson",
"Len Dawson",
"Fred Dean",
"edward debartolo jr",
"Joe DeLamielleure",
"Richard Dent",
"Eric Dickerson",
"Dan Dierdorf",
"Bobby Dillon",
"Mike Ditka",
"Chris Doleman",
"Art Donovan",
"Tony Dorsett",
"john paddy driscoll",
"Bill Dudley",
"Tony Dungy",
"Kenny Easley",
"albert glen turk edwards",
"Carl Eller",
"John Elway",
"Weeb Ewbank",
"Alan Faneca",
"Marshall Faulk",
"Brett Favre",
"Tom Fears",
"Jim Finks",
"Ray Flaherty",
"Tom Flores",
"Len Ford",
"Dan Fortmann",
"Dan Fouts",
"Benny Friedman",
"Frank Gatski",
"Bill George",
"Joe Gibbs",
"Frank Gifford",
"Sid Gillman",
"Tony Gonzalez",
"Otto Graham",
"Bud Grant",
"Darrell Green",
"Joe Greene",
"Kevin Greene",
"Forrest Gregg",
"Bob Griese",
"Russ Grimm",
"Lou Groza",
"Ray Guy",
"Joe Guyon",
"George Halas",
"Charles Haley",
"Jack Ham",
"Dan Hampton",
"Chris Hanburger",
"John Hannah",
"Cliff Harris",
"Franco Harris",
"Marvin Harrison",
"Bob Hayes",
"Mike Haynes",
"Ed Healey",
"Mel Hein",
"Ted Hendricks",
"Wilbur (Pete) Henry",
"Arnie Herber",
"Bill Hewitt",
"Gene Hickerson",
"Winston Hill",
"Clarke Hinkle",
"Paul Hornung",
"Ken Houston",
"Chuck Howley",
"Robert (Cal) Hubbard",
"Sam Huff",
"Claude Humphrey",
"Lamar Hunt",
"Steve Hutchinson",
"Don Hutson",
"Michael Irvin",
"Rickey Jackson",
"Edgerrin James",
"Calvin Johnson",
"Jimmy Johnson",
"Jimmy Johnson",
"John Henry Johnson",
"Charlie Joiner",
"David (Deacon) Jones",
"Jerry Jones",
"Stan Jones",
"Walter Jones",
"Henry Jordan",
"Sonny Jurgensen",
"Alex Karras",
"Jim Kelly",
"Leroy Kelly",
"Cortez Kennedy",
"Walt Kiesling",
"frank bruiser kinard",
"Joe Klecko",
"Jerry Kramer",
"Paul Krause",
"Earl 'Curly' Lambeau",
"Jack Lambert",
"Tom Landry",
"dick night train lane",
"Jim Langer",
"Willie Lanier",
"Steve Largent",
"Yale Lary",
"Dante Lavelli",
"Ty Law",
"Bobby Layne",
"Dick LeBeau",
"alphonse tuffy leemans",
"Marv Levy",
"Ray Lewis",
"Bob Lilly",
"Floyd Little",
"Larry Little",
"James Lofton",
"Vince Lombardi",
"Howie Long",
"Ronnie Lott",
"Sid Luckman",
"william roy link lyman",
"John Lynch",
"Tom Mack",
"John Mackey",
"John Madden",
"Peyton Manning",
"Tim Mara",
"Wellington Mara",
"Gino Marchetti",
"Dan Marino",
"George Preston Marshall",
"Curtis Martin",
"Ollie Matson",
"Bruce Matthews",
"Kevin Mawae",
"Don Maynard",
"George McAfee",
"Mike McCormack",
"Randall McDaniel",
"Tommy McDonald",
"Hugh McElhenny",
"Art McNally",
"john blood mcnally",
"Mike Michalske",
"Wayne Millner",
"Sam Mills",
"Bobby Mitchell",
"Ron Mix",
"Art Monk",
"Joe Montana",
"Warren Moon",
"Lenny Moore",
"Randy Moss",
"Marion Motley",
"Mike Munchak",
"anthony munoz",
"George Musso",
"Bronko Nagurski",
"Joe Namath",
"earle greasy neale",
"Ernie Nevers",
"Ozzie Newsome",
"Ray Nitschke",
"Chuck Noll",
"Leo Nomellini",
"Bill Nunn",
"Jonathan Ogden",
"Merlin Olsen",
"Jim Otto",
"Steve Owen",
"Terrell Owens",
"Orlando Pace",
"Alan Page",
"Bill Parcells",
"clarence ace parker",
"Jim Parker",
"Walter Payton",
"Drew Pearson",
"Joe Perry",
"Pete Pihos",
"Troy Polamalu",
"Bill Polian",
"Fritz Pollard",
"John Randle",
"hugh shorty ray",
"Andre Reed",
"Ed Reed",
"Dan Reeves",
"Mel Renfro",
"Darrelle Revis",
"Jerry Rice",
"Les Richter",
"John Riggins",
"Ken Riley",
"Jim Ringo",
"Willie Roaf",
"Dave Robinson",
"Johnny Robinson",
"Andy Robustelli",
"Art Rooney",
"Dan Rooney",
"Pete Rozelle",
"Ed Sabol",
"Steve Sabol",
"Barry Sanders",
"Charlie Sanders",
"Deion Sanders",
"Warren Sapp",
"Gale Sayers",
"Joe Schmidt",
"Tex Schramm",
"Junior Seau",
"Lee Roy Selmon",
"Richard Seymour",
"Shannon Sharpe",
"Billy Shaw",
"Art Shell",
"Donnie Shell",
"Will Shields",
"Don Shula",
"O.J. Simpson",
"Mike Singletary",
"Duke Slater",
"Jackie Slater",
"Bruce Smith",
"Emmitt Smith",
"Jackie Smith",
"Mac Speedie",
"Ed Sprinkle",
"Bob St. Clair",
"Ken Stabler",
"John Stallworth",
"Dick Stanfel",
"Bart Starr",
"Roger Staubach",
"Ernie Stautner",
"Jan Stenerud",
"Dwight Stephenson",
"Michael Strahan",
"Hank Stram",
"Ken Strong",
"Joe Stydahar",
"Lynn Swann",
"Paul Tagliabue",
"Fran Tarkenton",
"Charley Taylor",
"Jason Taylor",
"Jim Taylor",
"Lawrence Taylor",
"Derrick Thomas",
"Emmitt Thomas",
"Joe Thomas",
"Thurman Thomas",
"Zach Thomas",
"Jim Thorpe",
"Mick Tingelhoff",
"Andre Tippett",
"Y.A. Tittle",
"LaDainian Tomlinson",
"George Trafton",
"Charley Trippi",
"Emlen Tunnell",
"clyde bulldog turner",
"Johnny Unitas",
"Gene Upshaw",
"Brian Urlacher",
"Norm Van Brocklin",
"Steve Van Buren",
"Dick Vermeil",
"Doak Walker",
"Bill Walsh",
"DeMarcus Ware",
"Paul Warfield",
"Kurt Warner",
"Bob Waterfield",
"Mike Webster",
"Roger Wehrli",
"Arnie Weinmeister",
"Randy White",
"Reggie White",
"Dave Wilcox",
"Aeneas Williams",
"Bill Willis",
"Larry Wilson",
"Ralph Wilson, Jr.",
"Kellen Winslow",
"Alex Wojciechowicz",
"Ron Wolf",
"Willie Wood",
"Charles Woodson",
"Rod Woodson",
"Rayfield Wright",
"Ron Yary",
"Bryant Young",
"George Young",
"Steve Young",
"Jack Youngblood",
"Gary Zimmerman"

    # ... add all other names here ...
]


def remove_non_letters(name):
    return ''.join([char for char in name if char.isalpha() or char.isspace()])


def get_player_data(name):
    # Convert the name to the URL format
    url_name = remove_non_letters(name)
    url_name = url_name.lower().replace(" ", "-")
    
    url = BASE_URL + url_name + "/"
    
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Extract data using BeautifulSoup (this might need adjustments based on the exact HTML structure) player details__subinfo   
    statsAndPosiitons = soup.find_all("p", class_="player-details__subinfo")
    playersClassInfo = statsAndPosiitons[1].text
    playersClassInfo = playersClassInfo.replace('\n', "")
    playedPositions = statsAndPosiitons[0].text
    playedPositions = playedPositions.replace('\n', "")

    playerName = html.unescape(soup.find("h1", class_="player-details__name").text)
   

    bio = html.unescape(soup.find("div", class_="player-details__bio-container").text)
    bio = bio.replace('\n', "")

# Find all stat divs
    stat_divs = soup.find_all("div", class_="player-details__single-stat")
    

# Ensure the stats list is defined outside the loop
    stats = []

    for div in stat_divs:
        stat_topic = div.find("h2", class_="single-stat__title").text.strip()
        stat_value = div.find("p", class_="single-stat__number").text.strip()
        formatted_stat = f"{stat_topic}: {stat_value}"
    
    # Append each formatted stat to the stats list
        stats.append(formatted_stat)

# After the loop, join the formatted stats with a newline to separate them
    stats_text = ', '.join(stats)


    return {
        "name": playerName,
        "class": playersClassInfo,
        "Positions": playedPositions,
        "Stats": stats_text,
         "Bio": bio,
        # "position": position,
        # ... other data ...
    }

all_players_data = []

for name in player_names:
    try:
        player_data = get_player_data(name)
        all_players_data.append(player_data)
    except Exception as e:
        print(f"Error fetching data for {name}: {e}")

# Write to a file
with open('players_data.js', 'w') as file:
    file.write(json.dumps(all_players_data, indent=4))

print("Data written to players_data.js")
